"""
mock_igot_server.py — High-Fidelity iGOT Karmayogi / Sunbird Mock Server
=========================================================================
Loads seed data from ./data/ (generated by seed_data.py) into memory and
exposes Sunbird-compliant REST endpoints on Port 8001.

Architecture:
  • Every response is wrapped in the standard Sunbird envelope.
  • x-authenticated-user-token header is enforced on all protected routes.
  • Telemetry endpoint validates v3.1 payloads and de-duplicates by mid.
  • Content-state endpoint merges live in-memory state with seed snapshots.

Usage:
  pip install fastapi uvicorn faker
  python seed_data.py          # generate data first
  python mock_igot_server.py   # then start the server
"""

from __future__ import annotations

import json
import os
import random
import uuid
from datetime import datetime, timezone
from typing import Any

import uvicorn
from fastapi import FastAPI, Header, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel, field_validator

# ─────────────────────────────────────────────────────────────
# App bootstrap
# ─────────────────────────────────────────────────────────────

app = FastAPI(
    title="Mock iGOT Karmayogi API (Sunbird-Compliant)",
    description="High-fidelity standalone mock server for the MoSPI SIH Prototype.",
    version="3.1",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ─────────────────────────────────────────────────────────────
# In-Memory data stores (loaded from seed JSON files)
# ─────────────────────────────────────────────────────────────

DATA_DIR = os.path.join(os.path.dirname(__file__), "data")

def _load(filename: str) -> Any:
    path = os.path.join(DATA_DIR, filename)
    if not os.path.exists(path):
        raise RuntimeError(
            f"Data file '{filename}' not found. Please run seed_data.py first."
        )
    with open(path, encoding="utf-8") as f:
        return json.load(f)


# Populated at startup
DB_COURSES:          list[dict]  = []
DB_USERS:            list[dict]  = []
DB_ENROLLMENTS:      list[dict]  = []
DB_CONTENT_STATES:   dict[str, dict] = {}
DB_COMPETENCIES:     list[dict]  = []

# Runtime stores (grow during the server's lifetime)
TELEMETRY_STORE:     list[dict]  = []      # incoming telemetry events
SEEN_MIDS:           set[str]    = set()   # for deduplication
SCORE_PUSH_LOG:      list[dict]  = []      # synced scores from LMS
ENROLL_MUTATIONS:    dict[str, list] = {}  # userId -> newly enrolled records

@app.on_event("startup")
async def _startup():
    global DB_COURSES, DB_USERS, DB_ENROLLMENTS, DB_CONTENT_STATES, DB_COMPETENCIES
    DB_COURSES       = _load("course_catalog.json")
    DB_USERS         = _load("users.json")
    DB_ENROLLMENTS   = _load("enrollments.json")
    DB_CONTENT_STATES = _load("content_states.json")
    DB_COMPETENCIES  = _load("frac_competencies.json")
    print(f"[OK] Loaded {len(DB_COURSES)} courses, {len(DB_USERS)} users, "
          f"{len(DB_ENROLLMENTS)} enrolments, "
          f"{len(DB_CONTENT_STATES)} content-state snapshots.")

# ─────────────────────────────────────────────────────────────
# Sunbird Envelope factory
# ─────────────────────────────────────────────────────────────

def _ts_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S:%f")[:-3] + "+0000"

def sunbird_ok(api_id: str, ver: str, result: dict) -> dict:
    return {
        "id": api_id,
        "ver": ver,
        "ts": _ts_now(),
        "params": {
            "resmsgid": str(uuid.uuid4()),
            "msgid": str(uuid.uuid4()),
            "err": None,
            "status": "successful",
            "errmsg": None,
        },
        "responseCode": "OK",
        "result": result,
    }

def sunbird_err(api_id: str, ver: str, status_code: int, err_code: str, msg: str) -> JSONResponse:
    body = {
        "id": api_id,
        "ver": ver,
        "ts": _ts_now(),
        "params": {
            "resmsgid": str(uuid.uuid4()),
            "msgid": None,
            "err": err_code,
            "status": "failed",
            "errmsg": msg,
        },
        "responseCode": "BAD_REQUEST" if status_code == 400 else
                        "UNAUTHORIZED"        if status_code == 401 else
                        "RESOURCE_NOT_FOUND"  if status_code == 404 else
                        "INTERNAL_SERVER_ERROR",
        "result": {},
    }
    return JSONResponse(status_code=status_code, content=body)


# ─────────────────────────────────────────────────────────────
# Auth guard helper
# ─────────────────────────────────────────────────────────────

def _require_auth(token: str | None, api_id: str, ver: str) -> None:
    """Raises a JSONResponse (as HTTPException detail) when token is absent."""
    if not token:
        raise HTTPException(
            status_code=401,
            detail=sunbird_err(api_id, ver, 401, "ERR_UNAUTHORIZED",
                               "Mandatory header 'x-authenticated-user-token' is missing.").body.decode(),
        )


# ─────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────

def _user_by_id(user_id: str) -> dict | None:
    return next((u for u in DB_USERS if u["userId"] == user_id), None)

def _course_by_id(course_id: str) -> dict | None:
    return next((c for c in DB_COURSES if c["identifier"] == course_id), None)

def _user_enrolments(user_id: str) -> list[dict]:
    """Merge seed enrolments with any runtime mutations."""
    base = [e for e in DB_ENROLLMENTS if e["userId"] == user_id]
    mutations = ENROLL_MUTATIONS.get(user_id, [])
    return base + mutations


# ─────────────────────────────────────────────────────────────
# ① GET /api/content/read   — Course Catalog
# ─────────────────────────────────────────────────────────────

@app.get("/api/content/read")
async def get_course_catalog(
    request: Request,
    x_authenticated_user_token: str | None = Header(default=None),
):
    API_ID, VER = "api.content.read", "3.0"
    _require_auth(x_authenticated_user_token, API_ID, VER)

    # Honour optional ?identifier= query param to return a single course
    identifier = request.query_params.get("identifier")
    if identifier:
        course = _course_by_id(identifier)
        if not course:
            return sunbird_err(API_ID, VER, 404, "ERR_CONTENT_NOT_FOUND",
                               f"Content '{identifier}' not found.")
        return sunbird_ok(API_ID, VER, {"content": course})

    # Default: return full catalog summary
    return sunbird_ok(API_ID, VER, {
        "count": len(DB_COURSES),
        "content": DB_COURSES,
    })


# ─────────────────────────────────────────────────────────────
# ② GET /api/user/v2/read/{user_id}   — User Profile
# ─────────────────────────────────────────────────────────────

@app.get("/api/user/v2/read/{user_id}")
async def get_user_profile(
    user_id: str,
    x_authenticated_user_token: str | None = Header(default=None),
):
    API_ID, VER = "api.user.read", "v2"
    _require_auth(x_authenticated_user_token, API_ID, VER)

    user = _user_by_id(user_id)
    if not user:
        return sunbird_err(API_ID, VER, 404, "ERR_USER_NOT_FOUND",
                           f"User '{user_id}' does not exist.")

    return sunbird_ok(API_ID, VER, {"response": user})


# ─────────────────────────────────────────────────────────────
# ③ GET /api/course/v1/user/enrollment/list/{user_id}
# ─────────────────────────────────────────────────────────────

@app.get("/api/course/v1/user/enrollment/list/{user_id}")
async def get_user_enrolments(
    user_id: str,
    request: Request,
    x_authenticated_user_token: str | None = Header(default=None),
):
    API_ID, VER = "api.course.getuserenrolment", "v1"
    _require_auth(x_authenticated_user_token, API_ID, VER)

    user = _user_by_id(user_id)
    if not user:
        return sunbird_err(API_ID, VER, 404, "ERR_USER_NOT_FOUND",
                           f"User '{user_id}' does not exist.")

    enrolments = _user_enrolments(user_id)

    # Optional: enrich with course metadata if 'fields' param requested
    fields_param = request.query_params.get("fields", "")
    requested_fields = {f.strip() for f in fields_param.split(",") if f.strip()}

    enriched = []
    for enrol in enrolments:
        record = dict(enrol)
        if requested_fields:
            course = _course_by_id(enrol["courseId"])
            if course:
                for field in requested_fields:
                    if field in course:
                        record[field] = course[field]
        enriched.append(record)

    return sunbird_ok(API_ID, VER, {"courses": enriched})


# ─────────────────────────────────────────────────────────────
# ④ POST /api/course/v1/content/state/read
#    Pydantic schema for the request body
# ─────────────────────────────────────────────────────────────

class ContentStateRequest(BaseModel):
    request: dict

    @field_validator("request")
    @classmethod
    def _check_required_keys(cls, v: dict) -> dict:
        for key in ("userId", "courseId", "batchId"):
            if key not in v:
                raise ValueError(f"Missing required field in request: '{key}'")
        return v


@app.post("/api/course/v1/content/state/read")
async def get_content_state(
    body: ContentStateRequest,
    x_authenticated_user_token: str | None = Header(default=None),
):
    API_ID, VER = "api.content.state.read", "v1"
    _require_auth(x_authenticated_user_token, API_ID, VER)

    req     = body.request
    user_id = req["userId"]
    cid     = req["courseId"]
    bid     = req["batchId"]
    key     = f"{user_id}|{cid}|{bid}"

    state = DB_CONTENT_STATES.get(key)
    if not state:
        # Return empty contentList rather than 404 — mirrors Sunbird behaviour
        return sunbird_ok(API_ID, VER, {
            "contentList": [],
            "lastReadContentId": None,
            "completionPercentage": 0,
            "courseId": cid,
            "batchId": bid,
        })

    return sunbird_ok(API_ID, VER, state)


# ─────────────────────────────────────────────────────────────
# ⑤ POST /v1/telemetry
#    Validates v3.0 / v3.1 event batches with mid deduplication
# ─────────────────────────────────────────────────────────────

VALID_EIDS = {
    "START", "END", "IMPRESSION", "INTERACT", "ASSESS",
    "RESPONSE", "INTERRUPT", "FEEDBACK", "INDEX", "ERROR",
    "HEARTBEAT", "LOG", "SEARCH", "METRICS", "SUMMARY",
    "EXDATA", "AUDIT",
}

VALID_TELEMETRY_VERSIONS = {"3.0", "3.1"}


class TelemetryBatch(BaseModel):
    id:     str
    ver:    str
    ts:     str
    events: list[dict]

    @field_validator("ver")
    @classmethod
    def _ver_check(cls, v: str) -> str:
        if v not in VALID_TELEMETRY_VERSIONS:
            raise ValueError(f"Unsupported telemetry version: '{v}'. Must be 3.0 or 3.1")
        return v

    @field_validator("events")
    @classmethod
    def _events_not_empty(cls, v: list) -> list:
        if not v:
            raise ValueError("'events' array must not be empty.")
        return v


def _validate_event(event: dict) -> list[str]:
    """Returns a list of validation errors for a single telemetry event."""
    errors: list[str] = []
    mid = event.get("mid")

    if not event.get("eid") or event["eid"] not in VALID_EIDS:
        errors.append(f"Invalid or missing 'eid'. Got: {event.get('eid')!r}")
    if not isinstance(event.get("ets"), (int, float)):
        errors.append("'ets' must be a numeric epoch timestamp in milliseconds.")
    if not event.get("ver") or event["ver"] not in VALID_TELEMETRY_VERSIONS:
        errors.append(f"Invalid 'ver': {event.get('ver')!r}. Must be '3.0' or '3.1'.")
    if not mid:
        errors.append("'mid' (message ID) is required.")

    actor = event.get("actor", {})
    if not actor.get("id"):
        errors.append("actor.id is required.")
    if not actor.get("type"):
        errors.append("actor.type is required.")

    context = event.get("context", {})
    if not context.get("channel"):
        errors.append("context.channel is required.")
    if not context.get("env"):
        errors.append("context.env is required.")

    obj = event.get("object", {})
    if not obj.get("id"):
        errors.append("object.id is required.")
    if not obj.get("type"):
        errors.append("object.type is required.")

    return errors


@app.post("/v1/telemetry", status_code=200)
async def ingest_telemetry(
    batch: TelemetryBatch,
    x_authenticated_user_token: str | None = Header(default=None),
):
    API_ID, VER = "api.telemetry", "3.1"
    _require_auth(x_authenticated_user_token, API_ID, VER)

    accepted  = 0
    skipped   = 0
    rejected  = 0
    errors_log: list[dict] = []

    for event in batch.events:
        mid = event.get("mid")

        # Deduplication
        if mid and mid in SEEN_MIDS:
            skipped += 1
            continue

        # Schema validation
        errs = _validate_event(event)
        if errs:
            rejected += 1
            errors_log.append({"mid": mid, "errors": errs})
            continue

        # Accept
        TELEMETRY_STORE.append(event)
        if mid:
            SEEN_MIDS.add(mid)
        accepted += 1

    return sunbird_ok(API_ID, VER, {
        "message": "Telemetry batch processed.",
        "accepted": accepted,
        "skipped_duplicates": skipped,
        "rejected_invalid": rejected,
        "total_in_store": len(TELEMETRY_STORE),
        "validation_errors": errors_log if errors_log else None,
    })


# ─────────────────────────────────────────────────────────────
# Bonus: Legacy-compatible iGOT endpoints expected by our
#        MockIgotAdapter in main-lms-backend/adapters/
# ─────────────────────────────────────────────────────────────

class ScorePayload(BaseModel):
    competency_id: str
    new_level: int
    score_percentage: float
    passed: bool
    evaluated_at: str
    source: str


class EnrolPayload(BaseModel):
    igot_course_id: str
    enrolled_at: str


@app.get("/api/external/igot/catalog")
async def legacy_catalog():
    """Legacy endpoint consumed by MockIgotAdapter.fetch_catalog()"""
    return {
        "status": "success",
        "data": DB_COURSES,
    }


@app.get("/api/external/igot/users/{user_id}/history")
async def legacy_user_history(user_id: str):
    """Legacy endpoint consumed by MockIgotAdapter.fetch_user_history()"""
    enrolments = _user_enrolments(user_id)

    # Map to the simplified schema our adapter expects
    simplified = []
    for e in enrolments:
        status_str = (
            "COMPLETED"   if e["status"] == 2 else
            "IN_PROGRESS" if e["status"] == 1 else
            "NOT_STARTED"
        )
        simplified.append({
            "igot_course_id": e["courseId"],
            "course_title": e.get("courseName", ""),
            "status": status_str,
            "progress_percentage": e["completionPercentage"],
            "remaining_minutes": 0,
            "last_accessed_at": e.get("enrolledDate", ""),
        })

    return {"status": "success", "data": simplified}


@app.post("/api/external/igot/users/{user_id}/score", status_code=201)
async def legacy_push_score(user_id: str, payload: ScorePayload):
    SCORE_PUSH_LOG.append({"userId": user_id, **payload.model_dump()})
    return {"status": "success", "message": "Score synced to iGOT."}


@app.post("/api/external/igot/users/{user_id}/enroll", status_code=201)
async def legacy_enroll_user(user_id: str, payload: EnrolPayload):
    course = _course_by_id(payload.igot_course_id)
    if not course:
        return JSONResponse(status_code=404, content={"status": "error", "message": "Course not found."})

    new_record = {
        "active": True,
        "courseId": course["identifier"],
        "courseName": course["name"],
        "contentId": course["identifier"],
        "batchId": "batch_" + course["identifier"][3:] + "_01",
        "userId": user_id,
        "enrolledDate": payload.enrolled_at,
        "status": 0,
        "completionPercentage": 0,
        "progress": 0,
        "leafNodesCount": course["leafNodesCount"],
        "lastReadContentId": "",
        "lastReadContentStatus": 0,
        "issuedCertificates": [],
        "channel": course.get("channel", "igot-mdo-mospi-01"),
    }
    ENROLL_MUTATIONS.setdefault(user_id, []).append(new_record)
    return {"status": "success", "message": "User enrolled on iGOT."}


# ─────────────────────────────────────────────────────────────
# Health / introspection endpoints
# ─────────────────────────────────────────────────────────────

@app.get("/health")
async def health():
    return {
        "status": "ok",
        "server": "Mock iGOT Karmayogi (Sunbird-Compliant)",
        "port": 8001,
        "data_loaded": {
            "courses": len(DB_COURSES),
            "users": len(DB_USERS),
            "enrollments": len(DB_ENROLLMENTS),
            "content_state_snapshots": len(DB_CONTENT_STATES),
            "competencies": len(DB_COMPETENCIES),
        },
        "runtime": {
            "telemetry_events_ingested": len(TELEMETRY_STORE),
            "score_pushes_received": len(SCORE_PUSH_LOG),
            "runtime_enrolment_mutations": sum(len(v) for v in ENROLL_MUTATIONS.values()),
        }
    }


@app.get("/api/frac/competencies")
async def get_competencies(
    x_authenticated_user_token: str | None = Header(default=None),
):
    API_ID, VER = "api.frac.competencies.read", "v1"
    _require_auth(x_authenticated_user_token, API_ID, VER)
    return sunbird_ok(API_ID, VER, {
        "count": len(DB_COMPETENCIES),
        "competencies": DB_COMPETENCIES,
    })


# ─────────────────────────────────────────────────────────────
# Exception handler — ensure 401s from _require_auth
# keep Sunbird envelope format
# ─────────────────────────────────────────────────────────────

@app.exception_handler(HTTPException)
async def http_exc_handler(request: Request, exc: HTTPException):
    # If detail is already a JSON-encoded Sunbird envelope, return it raw
    if isinstance(exc.detail, str):
        try:
            body = json.loads(exc.detail)
            return JSONResponse(status_code=exc.status_code, content=body)
        except (json.JSONDecodeError, TypeError):
            pass
    return JSONResponse(
        status_code=exc.status_code,
        content={
            "id": "api.error",
            "ver": "v1",
            "ts": _ts_now(),
            "params": {"err": str(exc.status_code), "status": "failed", "errmsg": str(exc.detail)},
            "responseCode": "INTERNAL_SERVER_ERROR",
            "result": {},
        }
    )


if __name__ == "__main__":
    uvicorn.run("mock_igot_server:app", host="0.0.0.0", port=8001, reload=True)
