"""
FILE: routers/rag.py
─────────────────────────────────────────────────────────────────────────────
RAG Document-to-Quiz Router
MoSPI Skill Intelligence Platform | SIH 2026

Handles document ingestion (PDF, PPT, PPTX, TXT), validates payloads,
extracts cleaned plain-text using PyPDF / pdfplumber / python-pptx,
generates 5 grounded, cross-model-verified MCQs via ai/quiz (Groq + Gemini,
offline fallback), and provides quiz grading with automatic competency
syncing to iGOT.
─────────────────────────────────────────────────────────────────────────────
"""

import io
import os
import re
import json
import uuid
import asyncio
import logging
import zipfile
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from typing import Optional, Dict, Any, Tuple, List

import httpx
from dotenv import load_dotenv
from fastapi import APIRouter, File, Form, HTTPException, UploadFile, status
from pydantic import BaseModel, Field
from langchain_text_splitters import RecursiveCharacterTextSplitter

from ai.quiz import QuizBuildError, build_quiz
from auth.database import SessionLocal, engine, get_db
from auth.dependencies import get_current_user
from auth.models import UserAuth
from models.models import (
    Base,
    Competency,
    UserCompetency,
    CompetencyProfile,
    Official,
    Assessment,
    EvidenceLog,
    QuizAttempt,
)
from fastapi import Depends

# Load environment variables (GROQ_API_KEYS, GEMINI_API_KEY, IGOT_COMPETENCIES_UPDATE_URL)
load_dotenv()

# PDF Extraction libraries
try:
    import pdfplumber
except ImportError:
    pdfplumber = None

try:
    import pypdf
except ImportError:
    pypdf = None

# PPTX Extraction library
try:
    from pptx import Presentation
except ImportError:
    Presentation = None

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)

router = APIRouter()

# ── Configuration Constants ───────────────────────────────────────────────────
MAX_FILE_SIZE_BYTES = 25 * 1024 * 1024  # 25 MB max limit
SUPPORTED_EXTENSIONS = {".pdf", ".ppt", ".pptx", ".txt"}


# =============================================================================
# PYDANTIC SCHEMAS
# =============================================================================

class QuizQuestion(BaseModel):
    """Full question as stored server-side in QUIZ_STORE (never sent before grading)."""
    question: str = Field(..., description="The quiz question text")
    options: List[str] = Field(..., description="List of 4 multiple-choice options")
    correct_answer: int = Field(..., description="Zero-based index (0, 1, 2, or 3) of the correct option in options")
    explanation: str = Field(..., description="Detailed explanation for why the answer is correct")
    evidence: Optional[str] = Field(None, description="Verbatim document excerpt that proves the answer")
    source: Optional[str] = Field(None, description="Page/slide the evidence comes from, when known")
    bloom_level: Optional[str] = Field(None, description="recall | understand | apply | analyse")


class PublicQuizQuestion(BaseModel):
    """What the learner sees while taking the quiz — no answer key."""
    question: str
    options: List[str]
    bloom_level: Optional[str] = None


class QuestionReview(BaseModel):
    question: str
    options: List[str]
    your_answer: Optional[int] = Field(None, description="Submitted option index, or null if unanswered")
    correct_answer: int
    is_correct: bool
    explanation: str
    evidence: Optional[str] = None
    source: Optional[str] = None


class QuizPayload(BaseModel):
    questions: List[QuizQuestion] = Field(..., description="List of exactly 5 generated multiple-choice questions")


class DocumentMetadata(BaseModel):
    filename: str = Field(..., description="Original name of the uploaded file")
    file_type: str = Field(..., description="Detected file extension (.pdf, .ppt, .pptx, .txt)")
    file_size_bytes: int = Field(..., description="Size of the uploaded file in bytes")
    character_count: int = Field(..., description="Total extracted character count")
    word_count: int = Field(..., description="Total extracted word count")
    chunk_count: Optional[int] = Field(None, description="Total number of chunks generated by LangChain text splitter")
    page_count: Optional[int] = Field(None, description="Total number of pages (for PDF)")
    slide_count: Optional[int] = Field(None, description="Total number of slides (for PPT/PPTX)")
    line_count: Optional[int] = Field(None, description="Total number of lines (for TXT)")


class DocumentUploadResponse(BaseModel):
    status: str = Field("success", description="Status code or status description ('success' or 'error')")
    message: str = Field(..., description="Human-readable status summary")
    quiz_id: str = Field(..., description="Unique identifier for the generated quiz session")
    filename: str = Field(..., description="Uploaded document filename")
    file_type: str = Field(..., description="Document file type")
    questions: List[PublicQuizQuestion] = Field(..., description="Generated questions (answer key withheld until grading)")
    metadata: DocumentMetadata = Field(..., description="Structured metadata of the processed document")
    generation: Optional[Dict[str, Any]] = Field(None, description="Generator/checker models, verification mode and rejection counts")


class GradeRequest(BaseModel):
    # FIX (Bug #10): user_id removed from request body.
    # The authenticated user's iGOT userId is derived from current_user.username
    # (populated via JWT in Depends(get_current_user)).
    # Accepting user_id from the body allowed unauthenticated identity spoofing.
    quiz_id: str = Field(..., description="Unique ID of the quiz session being graded")
    answers: List[int] = Field(..., description="List of chosen option indices (0-indexed)")


class GradeResponse(BaseModel):
    status: str = Field("success", description="Status code or status description ('success' or 'error')")
    user_id: str = Field(..., description="User ID of the learner (from JWT)")
    quiz_id: str = Field(..., description="Quiz ID evaluated")
    score: float = Field(..., description="Percentage score achieved (0-100)")
    passed: bool = Field(..., description="True if score >= 70%, False otherwise")
    correct_count: int = Field(..., description="Number of correctly answered questions")
    total_questions: int = Field(..., description="Total number of questions in the quiz")
    message: str = Field(..., description="Human-readable result summary message")
    synced_to_igot: Optional[bool] = Field(None, description="Indicates whether the competency update was pushed to iGOT")
    igot_response: Optional[Dict[str, Any]] = Field(None, description="Response from the mock iGOT server if synced")
    db_updated: Optional[bool] = Field(None, description="Indicates whether the internal SQLite database was updated")
    # FIX (Bug #10): new field — True only on first submission
    evidenceWritten: Optional[bool] = Field(None, description="True if a new EvidenceLog row was written (first submission only)")
    review: List[QuestionReview] = Field(default_factory=list, description="Per-question answer review with source evidence")




class ErrorResponse(BaseModel):
    status: str = Field("error", description="Failure indicator")
    detail: str = Field(..., description="Error message details")


# =============================================================================
# IN-MEMORY QUIZ STORE
# =============================================================================

QUIZ_STORE: Dict[str, Dict[str, Any]] = {
    "quiz_demo": {
        "quiz_id": "quiz_demo",
        "questions": [
            QuizQuestion(
                question="What is the primary international standard for National Accounts?",
                options=["SNA 2008", "GDP 1993", "IMF 2020", "OECD 2015"],
                correct_answer=0,
                explanation="System of National Accounts (SNA 2008) is the international statistical standard."
            ),
            QuizQuestion(
                question="Which organisation compiles CPI-Combined in India?",
                options=["Reserve Bank of India", "NSO / MoSPI", "NITI Aayog", "Ministry of Finance"],
                correct_answer=1,
                explanation="NSO (National Statistical Office) under MoSPI compiles and releases CPI."
            ),
            QuizQuestion(
                question="What is the base year for the current CPI series in India?",
                options=["2004-05", "2011-12", "2012", "2016"],
                correct_answer=2,
                explanation="The current CPI series has base year 2012 = 100."
            ),
            QuizQuestion(
                question="Which sampling technique gives every unit an equal probability of selection?",
                options=["Simple Random Sampling", "Judgment Sampling", "Quota Sampling", "Snowball Sampling"],
                correct_answer=0,
                explanation="Simple Random Sampling (SRS) ensures equal inclusion probability."
            ),
            QuizQuestion(
                question="What formula is predominantly used for consumer price indices in India?",
                options=["Laspeyres formula", "Fisher ideal index", "Törnqvist index", "Divisia index"],
                correct_answer=0,
                explanation="Laspeyres base-weighted formula is standard in CPI compilation."
            )
        ],
        "filename": "sample_mospi_overview.pdf",
        "competency_id": "FRAC-STAT-001",
        "skill_name": "National Accounts & Official Statistics",
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
}


# =============================================================================
# TEXT EXTRACTION HELPERS
# =============================================================================

def _clean_text(text: str) -> str:
    """
    Normalizes whitespace, removes null bytes, and cleans up repeated linebreaks.
    """
    if not text:
        return ""
    # Remove null bytes
    text = text.replace("\x00", "")
    # Normalize carriage returns
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    # Replace multiple continuous whitespace (except single newlines)
    text = re.sub(r"[ \t]+", " ", text)
    # Condense 3+ newlines to double newline
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def _extract_pdf(file_bytes: bytes) -> Tuple[str, int]:
    """
    Extracts text from PDF bytes using pdfplumber (primary) with fallback to pypdf.
    Returns a tuple of (extracted_text, page_count).
    """
    extracted_pages = []
    page_count = 0

    # 1. Attempt extraction with pdfplumber (superior layout & table preservation)
    if pdfplumber is not None:
        try:
            with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
                page_count = len(pdf.pages)
                for idx, page in enumerate(pdf.pages, start=1):
                    page_text = page.extract_text() or ""
                    if page_text.strip():
                        extracted_pages.append(f"--- Page {idx} ---\n{page_text.strip()}")
            
            combined_text = "\n\n".join(extracted_pages)
            if combined_text.strip():
                return _clean_text(combined_text), page_count
        except Exception as e:
            logger.warning(f"pdfplumber failed: {e}. Falling back to pypdf.")
            extracted_pages.clear()

    # 2. Fallback to pypdf
    if pypdf is not None:
        try:
            reader = pypdf.PdfReader(io.BytesIO(file_bytes))
            page_count = len(reader.pages)
            for idx, page in enumerate(reader.pages, start=1):
                page_text = page.extract_text() or ""
                if page_text.strip():
                    extracted_pages.append(f"--- Page {idx} ---\n{page_text.strip()}")
            
            combined_text = "\n\n".join(extracted_pages)
            return _clean_text(combined_text), page_count
        except Exception as e:
            logger.error(f"pypdf extraction failed: {e}")
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail=f"Could not parse PDF content: {str(e)}"
            )

    raise HTTPException(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        detail="No PDF extraction library available on the server (pdfplumber/pypdf)."
    )


def _extract_pptx(file_bytes: bytes) -> Tuple[str, int]:
    """
    Extracts text from PPTX files using python-pptx with XML fallback.
    Returns a tuple of (extracted_text, slide_count).
    """
    slide_texts = []
    slide_count = 0

    # 1. Primary extraction via python-pptx
    if Presentation is not None:
        try:
            prs = Presentation(io.BytesIO(file_bytes))
            slide_count = len(prs.slides)

            for idx, slide in enumerate(prs.slides, start=1):
                parts = []
                # Extract slide shape texts (titles, textboxes, tables)
                for shape in slide.shapes:
                    if shape.has_text_frame:
                        for paragraph in shape.text_frame.paragraphs:
                            text = "".join(run.text for run in paragraph.runs).strip()
                            if text:
                                parts.append(text)
                    elif shape.has_table:
                        for row in shape.table.rows:
                            row_text = " | ".join(cell.text.strip() for cell in row.cells if cell.text.strip())
                            if row_text:
                                parts.append(row_text)

                # Extract speaker notes if available
                if slide.has_notes_slide and slide.notes_slide.notes_text_frame:
                    notes = slide.notes_slide.notes_text_frame.text.strip()
                    if notes:
                        parts.append(f"[Notes: {notes}]")

                if parts:
                    slide_texts.append(f"--- Slide {idx} ---\n" + "\n".join(parts))

            combined_text = "\n\n".join(slide_texts)
            if combined_text.strip():
                return _clean_text(combined_text), slide_count
        except Exception as e:
            logger.warning(f"python-pptx failed: {e}. Attempting direct XML parsing.")
            slide_texts.clear()

    # 2. Fallback: Parse slide XML files from PPTX (ZIP container) directly
    try:
        with zipfile.ZipFile(io.BytesIO(file_bytes)) as z:
            slide_files = [f for f in z.namelist() if f.startswith("ppt/slides/slide") and f.endswith(".xml")]
            slide_count = len(slide_files)
            # Sort numerically by slide number
            slide_files.sort(key=lambda name: int(re.search(r"\d+", name).group()) if re.search(r"\d+", name) else 0)

            for idx, slide_file in enumerate(slide_files, start=1):
                xml_content = z.read(slide_file)
                tree = ET.fromstring(xml_content)
                # PPTX text elements are in the 'a:t' tags
                texts = [elem.text for elem in tree.iter() if elem.tag.endswith("}t") and elem.text]
                if texts:
                    slide_texts.append(f"--- Slide {idx} ---\n" + "\n".join(texts))

            combined_text = "\n\n".join(slide_texts)
            return _clean_text(combined_text), slide_count
    except Exception as e:
        logger.error(f"PPTX extraction error: {e}")
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"Could not parse PowerPoint presentation: {str(e)}"
        )


def _extract_txt(file_bytes: bytes) -> Tuple[str, int]:
    """
    Extracts text from plain text bytes trying multiple character encodings.
    Returns a tuple of (extracted_text, line_count).
    """
    encodings = ["utf-8", "utf-8-sig", "latin-1", "cp1252", "iso-8859-1"]
    decoded_text = None

    for enc in encodings:
        try:
            decoded_text = file_bytes.decode(enc)
            break
        except UnicodeDecodeError:
            continue

    if decoded_text is None:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="Unable to decode text file. Ensure it is encoded in UTF-8 or standard ASCII."
        )

    cleaned = _clean_text(decoded_text)
    line_count = len(decoded_text.splitlines())
    return cleaned, line_count


def _chunk_document_text(text: str, chunk_size: int = 1000, chunk_overlap: int = 150) -> List[str]:
    """
    Splits extracted document plain-text into semantically coherent chunks using
    LangChain's RecursiveCharacterTextSplitter for RAG processing and vector indexing.
    """
    if not text or not text.strip():
        return []

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
        separators=["\n\n", "\n", ". ", " ", ""],
        length_function=len,
    )
    return splitter.split_text(text)


def _detect_skill_name(text: str = "", filename: str = "") -> str:
    """
    Infers or extracts the skill/competency topic dynamically from the document's
    filename and text content. Falls back to 'General Statistics' if no match.
    """
    combined = f"{filename} {text[:4000]}".lower()

    if any(k in combined for k in ["machine learning", "supervised learning", "unsupervised learning", "deep learning", "neural network", "classification model"]):
        return "Machine Learning"
    if any(k in combined for k in ["generative ai", "genai", "llm", "large language model", "transformer", "diffusion"]):
        return "Generative AI"
    if any(k in combined for k in ["national account", "gdp", "gross domestic product", "gva", "national income", "macroeconomic indicator"]):
        return "National Accounts"
    if any(k in combined for k in ["data analysis", "data analytics", "exploratory data", "data visualization", "descriptive statistics"]):
        return "Data Analysis"
    if any(k in combined for k in ["index number", "cpi", "wpi", "consumer price index", "wholesale price", "inflation index"]):
        return "Index Numbers"
    if any(k in combined for k in ["sample survey", "sampling design", "nsso", "stratified sampling", "survey methodology", "multistage sampling"]):
        return "Sample Surveys"
    if any(k in combined for k in ["official statistics", "statistical system", "mospi", "cso", "nsso"]):
        return "Official Statistics"
    if any(k in combined for k in ["time series", "forecasting", "arima", "seasonality", "trend analysis"]):
        return "Time Series Analysis"
    if any(k in combined for k in ["python", "pandas", "numpy", "scikit-learn"]):
        return "Python for Data Science"
    if any(k in combined for k in ["sql", "database", "relational database", "query"]):
        return "Database Management"

    return "General Statistics"


def _update_internal_db_competency(
    user_id: str,
    competency_name: str = "General Statistics",
    default_level: int = 3,
    score: float = 0.0,
    quiz_id: str = "",
) -> Tuple[bool, int]:
    """
    Updates the internal auth.db SQLite database via SQLAlchemy models:
    1. Only executed when passed == True.
    2. Uses the correct column name `profileId` (NOT user_id).
    3. Checks if the user exists in the `competency_profiles` table.
    4. If user EXISTS: increases their current_level by 1 (capped at max level 5).
    5. If user DOES NOT EXIST: creates a new record with:
       - profileId = payload.user_id
       - skill_name = dynamically determined skill name
       - current_level = 3 (baseline passing level)
       - target_level = 4
       - updated_at = current timestamp
    6. Explicitly sets these values in INSERT/UPDATE statements so they override database defaults.
    7. Commits changes to the database.
    8. Robust error handling ensures the endpoint never crashes on database errors.
    Returns: (success: bool, final_level: int)
    """
    final_level = default_level
    try:
        Base.metadata.create_all(bind=engine)
        db = SessionLocal()
        try:
            # 1. Find or create Competency for the dynamic skill_name
            comp = db.query(Competency).filter(Competency.skillName == competency_name).first()
            if not comp:
                comp = Competency(
                    compId=f"COMP-{uuid.uuid4().hex[:6].upper()}",
                    domain="Statistical",
                    skillName=competency_name,
                )
                db.add(comp)
                db.flush()

            # 2. Check if user exists in competency_profiles table using profileId
            profile = db.query(CompetencyProfile).filter(CompetencyProfile.profileId == user_id).first()

            if profile:
                logger.info(f"User '{user_id}' EXISTS in competency_profiles. Updating skill '{competency_name}'.")
                profile.skill_name = competency_name
                profile.lastEvaluatedDate = datetime.now(timezone.utc)
                
                # Check UserCompetency record for this profile and competency
                user_comp = db.query(UserCompetency).filter(
                    UserCompetency.profileId == profile.profileId,
                    UserCompetency.compId == comp.compId,
                ).first()

                existing_level = getattr(profile, "current_level", None) or 1

                if user_comp:
                    old_level = user_comp.currentLevel or existing_level or 1
                    final_level = min(old_level + 1, 5)  # increment by 1, capped at max level 5
                    user_comp.currentLevel = final_level
                    user_comp.evaluatedAt = datetime.now(timezone.utc)
                    user_comp.verificationSource = f"RAG Assessment Quiz ({quiz_id})"
                    logger.info(f"User '{user_id}' skill '{competency_name}' increased from Level {old_level} to Level {final_level}")
                else:
                    # User exists in profile table, but first assessment for this skill
                    final_level = default_level  # baseline level 3
                    user_comp = UserCompetency(
                        profileId=profile.profileId,
                        compId=comp.compId,
                        currentLevel=final_level,
                        verificationSource=f"RAG Assessment Quiz ({quiz_id})",
                        evaluatedAt=datetime.now(timezone.utc),
                    )
                    db.add(user_comp)
                    logger.info(f"Created new UserCompetency for user '{user_id}' skill '{competency_name}' at Level {final_level}")

                profile.current_level = final_level
                profile.target_level = min(final_level + 1, 5)
            else:
                logger.info(f"User '{user_id}' DOES NOT EXIST in competency_profiles. Creating new record.")
                final_level = default_level  # baseline level 3
                profile = CompetencyProfile(
                    profileId=user_id,
                    skill_name=competency_name,
                    current_level=final_level,
                    target_level=4,
                    lastEvaluatedDate=datetime.now(timezone.utc),
                )
                db.add(profile)
                db.flush()

                user_comp = UserCompetency(
                    profileId=profile.profileId,
                    compId=comp.compId,
                    currentLevel=final_level,
                    verificationSource=f"RAG Assessment Quiz ({quiz_id})",
                    evaluatedAt=datetime.now(timezone.utc),
                )
                db.add(user_comp)
                logger.info(f"Created new CompetencyProfile with profileId='{user_id}', skill_name='{competency_name}', current_level={final_level}")

            # 3. Save assessment audit entry
            if quiz_id:
                assessment = Assessment(
                    assessmentId=quiz_id,
                    passingScore=70.0,
                    sourceDocumentId=f"RAG Assessment ({competency_name})",
                )
                db.merge(assessment)

            # 4. Commit changes to SQLite auth.db
            db.commit()
            logger.info(f"Successfully committed competency update to auth.db: profileId='{user_id}', skill='{competency_name}', level={final_level}")
            return True, final_level
        except Exception as ex:
            db.rollback()
            logger.exception(f"Failed to update internal auth.db for user {user_id}: {ex}")
            return False, final_level
        finally:
            db.close()
    except Exception as e:
        logger.exception(f"Database connection error updating competency for user {user_id}: {e}")
        return False, final_level


# =============================================================================
# QUIZ GENERATION HELPER (ai/quiz pipeline)
# =============================================================================

async def _generate_mcqs_from_text(
    text: str,
    chunks: Optional[List[str]] = None,
    difficulty: str = "Medium",
    num_questions: int = 5,
) -> Tuple[List[QuizQuestion], Dict[str, Any]]:
    """
    Builds grounded MCQs with ai.quiz.build_quiz: one model family writes them,
    a deterministic gate checks every evidence quote against the document, and a
    different model family answers each question blind; only agreed questions are
    kept. Groq keys/models and Gemini fail over to each other, and an extractive
    offline builder covers the case where every provider is down.
    """
    try:
        result = await build_quiz(text, chunks or [text], n=num_questions, difficulty=difficulty)
    except QuizBuildError as exc:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail=str(exc))
    except Exception as exc:
        logger.exception("Quiz generation failed: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Quiz generation failed: {exc}",
        )

    questions = [
        QuizQuestion(
            question=c.question,
            options=c.options,
            correct_answer=c.correct_answer,
            explanation=c.explanation or f"The document states: “{c.evidence}”",
            evidence=c.evidence,
            source=c.location,
            bloom_level=c.bloom_level,
        )
        for c in result.questions
    ]
    return questions, result.meta


# =============================================================================
# ENDPOINTS
# =============================================================================

@router.post(
    "/upload",
    response_model=DocumentUploadResponse,
    status_code=status.HTTP_200_OK,
    summary="Upload document, extract text, and generate 5 grounded, cross-verified quiz MCQs",
    responses={
        200: {"description": "Document parsed and MCQs generated and verified."},
        400: {"model": ErrorResponse, "description": "Invalid file format or empty payload."},
        413: {"model": ErrorResponse, "description": "File exceeds maximum size limit."},
        422: {"model": ErrorResponse, "description": "Unprocessable document, no readable text, or too little content for a reliable quiz."},
        500: {"model": ErrorResponse, "description": "Internal server processing or configuration error."},
        502: {"model": ErrorResponse, "description": "Unexpected error during generation."},
    },
)
async def upload_document_for_rag(
    file: UploadFile = File(..., description="Document file to process (.pdf, .ppt, .pptx, .txt)"),
    difficulty: str = Form("Medium", description="Easy | Medium | Hard"),
) -> DocumentUploadResponse:
    """
    **RAG Document Ingestion & Quiz Generator**

    - Accepts **PDF**, **PPT/PPTX**, and **TXT** files (max 25MB).
    - Extracts clean plain text with page/slide context using **pdfplumber / PyPDF / python-pptx**.
    - Builds 5 MCQs with `ai.quiz.build_quiz` at the requested difficulty: diverse
      passages → one model family generates → evidence quotes checked against the
      document → a second model family answers blind → only agreed questions kept.
    - Stores the full quiz (with answer key) in-memory under `quiz_id`; the response
      carries questions and options only.
    """
    # 1. Validate presence of filename
    if not file.filename:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No filename provided in upload payload."
        )

    filename = os.path.basename(file.filename)
    _, ext = os.path.splitext(filename.lower())

    # 2. Validate file extension
    if ext not in SUPPORTED_EXTENSIONS:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=(
                f"Unsupported file format '{ext}'. "
                f"Allowed document formats: {', '.join(sorted(SUPPORTED_EXTENSIONS))}"
            )
        )

    # 3. Read file content safely
    try:
        file_bytes = await file.read()
    except Exception as e:
        logger.error(f"Error reading uploaded stream for {filename}: {e}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Failed to read uploaded file: {str(e)}"
        )
    finally:
        await file.close()

    # 4. Validate file size
    file_size = len(file_bytes)
    if file_size == 0:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="The uploaded file is empty (0 bytes)."
        )

    if file_size > MAX_FILE_SIZE_BYTES:
        max_mb = MAX_FILE_SIZE_BYTES // (1024 * 1024)
        raise HTTPException(
            status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
            detail=f"File size exceeds maximum allowed limit of {max_mb} MB."
        )

    # 5. Extract text based on file type
    page_count: Optional[int] = None
    slide_count: Optional[int] = None
    line_count: Optional[int] = None
    extracted_text = ""

    try:
        if ext == ".pdf":
            extracted_text, page_count = _extract_pdf(file_bytes)
        elif ext in {".ppt", ".pptx"}:
            if ext == ".ppt":
                # Check if it's actually a PPTX named .ppt or legacy PPT
                if file_bytes.startswith(b"PK\x03\x04"):
                    extracted_text, slide_count = _extract_pptx(file_bytes)
                else:
                    raise HTTPException(
                        status_code=status.HTTP_400_BAD_REQUEST,
                        detail="Legacy binary .ppt files must be converted to .pptx format or PDF."
                    )
            else:
                extracted_text, slide_count = _extract_pptx(file_bytes)
        elif ext == ".txt":
            extracted_text, line_count = _extract_txt(file_bytes)

    except HTTPException:
        raise
    except Exception as e:
        logger.exception(f"Unexpected error extracting text from {filename}: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Internal error processing document: {str(e)}"
        )

    # 6. Verify that readable text was obtained
    if not extracted_text or len(extracted_text.strip()) == 0:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=(
                "No readable text could be extracted from this document. "
                "If this is a scanned PDF/image, please provide a document with OCR/selectable text."
            )
        )

    # 6. Chunk extracted text using LangChain TextSplitter
    chunks = _chunk_document_text(extracted_text, chunk_size=1000, chunk_overlap=150)
    chunk_count = len(chunks)

    # 7. Generate and verify 5 MCQs from the most informative passages
    questions, generation = await _generate_mcqs_from_text(extracted_text, chunks=chunks, difficulty=difficulty)

    # 8. Generate unique quiz ID and store in-memory for subsequent grading
    inferred_skill = _detect_skill_name(text=extracted_text, filename=filename)
    quiz_id = f"QZ-{uuid.uuid4().hex[:8].upper()}"
    QUIZ_STORE[quiz_id] = {
        "quiz_id": quiz_id,
        "questions": questions,
        "filename": filename,
        "extracted_text": extracted_text[:4000],
        "chunks": chunks,
        "chunk_count": chunk_count,
        "competency_id": "FRAC-STAT-001",
        "skill_name": inferred_skill,
        "difficulty": generation.get("difficulty", difficulty),
        "generation": generation,
        "created_at": datetime.now(timezone.utc).isoformat(),
    }

    # 9. Compute statistics & build response metadata
    char_count = len(extracted_text)
    word_count = len(extracted_text.split())

    metadata = DocumentMetadata(
        filename=filename,
        file_type=ext,
        file_size_bytes=file_size,
        character_count=char_count,
        word_count=word_count,
        chunk_count=chunk_count,
        page_count=page_count,
        slide_count=slide_count,
        line_count=line_count,
    )

    return DocumentUploadResponse(
        status="success",
        message=f"Successfully chunked ({chunk_count} chunks) and generated {len(questions)} quiz questions from {filename}.",
        quiz_id=quiz_id,
        filename=filename,
        file_type=ext,
        questions=[PublicQuizQuestion(question=q.question, options=q.options, bloom_level=q.bloom_level) for q in questions],
        metadata=metadata,
        generation=generation,
    )


@router.post(
    "/grade",
    response_model=GradeResponse,
    status_code=status.HTTP_200_OK,
    summary="Grade submitted quiz answers and sync competency update to iGOT if passed",
    responses={
        200: {"description": "Quiz evaluated successfully."},
        400: {"model": ErrorResponse, "description": "Invalid submission or answers format."},
        401: {"model": ErrorResponse, "description": "Authentication required."},
        404: {"model": ErrorResponse, "description": "Quiz session not found."},
        500: {"model": ErrorResponse, "description": "Internal grading error."},
    },
)
async def grade_quiz(
    payload: GradeRequest,
    current_user: UserAuth = Depends(get_current_user),   # FIX (Bug #10): auth required
) -> GradeResponse:
    """
    **Grade Quiz & Sync Competency to Internal DB & Mock iGOT Server**

    FIX (Bug #10): Requires a valid JWT (Bearer token). user_id is derived
    from current_user.username (the iGOT userId like usr_XXXXXXXXX) — never
    from the request body (which was spoofable).

    FIX (Bug #10) Idempotency: A QuizAttempt row with UNIQUE(userId, quizId)
    is written BEFORE evidence. If the same user submits the same quiz again,
    the score is re-calculated for UX but NO second EvidenceLog row is written.

    FIX (Bug #9): On pass + first submission, writes an EvidenceLog row with:
      evidenceType = "PRACTICE_ASSESSMENT"
      userId       = current_user.username (iGOT userId, same identity space
                     as BaselineAssembler.compute_for_user)
      grantedValue = clamp(2.5 + (score-70)/30 * 1.5, 2.5, 4.0)

    The _update_internal_db_competency helper is kept for backward-compat UI
    display of db_updated field and the legacy CompetencyProfile table.
    """
    # Derive iGOT userId from JWT (Bug #10)
    igot_user_id = current_user.username   # e.g. "usr_720465595"

    # 1. Validate quiz existence in store
    quiz = QUIZ_STORE.get(payload.quiz_id)
    if not quiz:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Quiz session '{payload.quiz_id}' not found. Please upload a document to generate a quiz.",
        )

    questions: List[QuizQuestion] = quiz.get("questions", [])
    total_questions = len(questions)

    if total_questions == 0:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="The specified quiz contains no questions to grade.",
        )

    # 2. Validate answers list
    if payload.answers is None or len(payload.answers) == 0:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No answers provided in submission payload.",
        )

    # 3. Calculate score and build the per-question review
    correct_count = 0
    review: List[QuestionReview] = []
    for idx, question in enumerate(questions):
        given = payload.answers[idx] if idx < len(payload.answers) else None
        is_correct = given == question.correct_answer
        correct_count += is_correct
        review.append(QuestionReview(
            question=question.question,
            options=question.options,
            your_answer=given if given is not None and 0 <= given < len(question.options) else None,
            correct_answer=question.correct_answer,
            is_correct=is_correct,
            explanation=question.explanation,
            evidence=question.evidence,
            source=question.source,
        ))

    score_percentage = round((correct_count / total_questions) * 100.0, 2)
    passed = score_percentage >= 70.0

    # 4. Idempotency check + evidence write (Bug #10 + #9)
    synced_to_igot: Optional[bool] = None
    igot_response_data: Optional[Dict[str, Any]] = None
    db_updated: Optional[bool] = None
    evidence_written: Optional[bool] = None
    already_recorded = False
    final_level: int = 3

    def _grant_value_for_score(score: float) -> float:
        """Maps pass score [70,100] → evidence level [2.5, 4.0] (Bug #10)."""
        return round(max(2.5, min(4.0, 2.5 + (score - 70) / 30 * 1.5)), 2)

    # Write QuizAttempt row (idempotency) + EvidenceLog (Bug #9) if first attempt
    db = SessionLocal()
    try:
        existing_attempt = db.query(QuizAttempt).filter(
            QuizAttempt.userId == igot_user_id,
            QuizAttempt.quizId == payload.quiz_id,
        ).first()

        if existing_attempt:
            # Re-submission: return score for UX, do NOT write new evidence
            evidence_written = False
            already_recorded = bool(existing_attempt.evidenceWritten)
            logger.info(
                "[grade_quiz] Re-submission detected for user=%s quiz=%s — skipping evidence write.",
                igot_user_id, payload.quiz_id,
            )
        else:
            # First submission: persist attempt record
            quiz_comp_id = quiz.get("competency_id") or None
            attempt = QuizAttempt(
                userId          = igot_user_id,
                quizId          = payload.quiz_id,
                compId          = quiz_comp_id,
                answers         = payload.answers,
                score           = score_percentage,
                passed          = passed,
                evidenceWritten = False,
            )
            db.add(attempt)
            db.flush()   # get attemptId without committing yet

            if passed:
                # FIX (Bug #9): write EvidenceLog keyed by iGOT userId
                granted = _grant_value_for_score(score_percentage)

                # Try to resolve comp_id to a real Competency row
                comp_obj = None
                if quiz_comp_id:
                    comp_obj = db.query(Competency).filter(
                        Competency.compId == quiz_comp_id
                    ).first()
                if not comp_obj:
                    # Fallback: find/create by skill name
                    skill_name = quiz.get("skill_name", "General Statistics")
                    comp_obj = db.query(Competency).filter(
                        Competency.skillName == skill_name
                    ).first()
                    if not comp_obj:
                        comp_obj = Competency(
                            compId    = f"COMP-{uuid.uuid4().hex[:6].upper()}",
                            domain    = "Statistical",
                            skillName = skill_name,
                        )
                        db.add(comp_obj)
                        db.flush()

                from datetime import timezone as _tz
                evidence_row = EvidenceLog(
                    userId       = igot_user_id,           # iGOT userId (Bug #9)
                    compId       = comp_obj.compId,
                    evidenceType = "PRACTICE_ASSESSMENT",  # (Bug #9)
                    grantedValue = granted,                # formula, not +1 (Bug #10)
                    issueDate    = datetime.now(_tz.utc),
                    metadata_payload = {
                        "quiz_id":    payload.quiz_id,
                        "score":      score_percentage,
                        "pass_threshold": 70.0,
                    },
                )
                db.add(evidence_row)
                attempt.evidenceWritten = True
                evidence_written = True
                logger.info(
                    "[grade_quiz] EvidenceLog written: user=%s comp=%s granted=%.2f",
                    igot_user_id, comp_obj.compId, granted,
                )
            else:
                evidence_written = False

            db.commit()

    except Exception as exc:
        db.rollback()
        evidence_written = False
        logger.exception("[grade_quiz] DB error during QuizAttempt/EvidenceLog write: %s", exc)
    finally:
        db.close()

    # 5. If passed: update legacy CompetencyProfile table + sync to iGOT
    if passed:
        skill_name = (
            quiz.get("skill_name")
            or quiz.get("competency")
            or _detect_skill_name(text=quiz.get("extracted_text", ""), filename=quiz.get("filename", ""))
            or "General Statistics"
        )

        # A. Update legacy internal DB (backward-compat — drives db_updated response field)
        db_updated, final_level = _update_internal_db_competency(
            user_id=igot_user_id,
            competency_name=skill_name,
            default_level=3,
            score=score_percentage,
            quiz_id=payload.quiz_id,
        )

        # B. Sync with mock iGOT server
        igot_url   = os.getenv("IGOT_COMPETENCIES_UPDATE_URL", "http://localhost:8001/competencies/update")
        igot_token = os.getenv("IGOT_MOCK_TOKEN", "mock-api-key-2026")
        update_payload = {
            "user_id":   igot_user_id,
            "competency": skill_name,
            "new_level":  final_level,
        }
        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                resp = await client.post(
                    igot_url,
                    json=update_payload,
                    headers={"x-authenticated-user-token": igot_token},
                )
                if resp.status_code in (200, 201):
                    synced_to_igot = True
                    try:
                        igot_response_data = resp.json()
                    except Exception:
                        igot_response_data = {"status": "success", "raw": resp.text}
                else:
                    synced_to_igot = False
                    igot_response_data = {"status_code": resp.status_code, "response": resp.text}
        except httpx.RequestError as exc:
            synced_to_igot = False
            igot_response_data = {"warning": f"iGOT server unreachable at {igot_url}: {str(exc)}"}
        except Exception as exc:
            synced_to_igot = False
            igot_response_data = {"error": str(exc)}

    # 6. Build response message
    if passed:
        msg = f"Passed! You scored {score_percentage}% ({correct_count}/{total_questions} correct)."
        if db_updated:
            msg += f" Competency profile updated to Level {final_level}."
        if evidence_written:
            msg += " Practice assessment evidence recorded for skill gap analysis."
        elif already_recorded:
            msg += " (Evidence already recorded from a previous submission.)"
        if synced_to_igot:
            msg += " Synced to iGOT."
        elif synced_to_igot is False:
            msg += " (iGOT sync unavailable — internal DB updated.)"
    else:
        msg = (
            f"Did not pass. You scored {score_percentage}% ({correct_count}/{total_questions} correct). "
            "A minimum score of 70% is required to update your competency profile."
        )

    return GradeResponse(
        status          = "success",
        user_id         = igot_user_id,
        quiz_id         = payload.quiz_id,
        score           = score_percentage,
        passed          = passed,
        correct_count   = correct_count,
        total_questions = total_questions,
        message         = msg,
        synced_to_igot  = synced_to_igot,
        igot_response   = igot_response_data,
        db_updated      = db_updated,
        evidenceWritten = evidence_written,
        review          = review,
    )


