"""
FILE: routers/rag.py
─────────────────────────────────────────────────────────────────────────────
RAG Document-to-Quiz Router
MoSPI Skill Intelligence Platform | SIH 2026

Handles document ingestion (PDF, PPT, PPTX, TXT), validates payloads,
extracts cleaned plain-text using PyPDF / pdfplumber / python-pptx,
generates exactly 5 MCQs using Google Gemini API with strict JSON schema,
and provides quiz grading with automatic competency syncing to iGOT.
─────────────────────────────────────────────────────────────────────────────
"""

import io
import os
import re
import json
import uuid
import asyncio
import logging
import zipfile
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from typing import Optional, Dict, Any, Tuple, List

import httpx
from dotenv import load_dotenv
from fastapi import APIRouter, File, Form, HTTPException, UploadFile, status
from pydantic import BaseModel, Field

from auth.database import SessionLocal, engine, get_db
from auth.dependencies import get_current_user
from auth.models import UserAuth
from models.models import (
    Base,
    Competency,
    UserCompetency,
    CompetencyProfile,
    Official,
    Assessment,
    EvidenceLog,
    QuizAttempt,
)
from fastapi import Depends
from services import app_state
from services import practice_assessment as pa

# Load environment variables (such as GEMINI_API_KEY, IGOT_COMPETENCIES_UPDATE_URL)
load_dotenv()

# PDF/PPTX extraction, LangChain and Gemini are imported inside the functions
# that use them: langchain_text_splitters alone pulls in torch + transformers
# (~20 s), which kept the server from binding its port at startup.

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)

router = APIRouter()

# ── Configuration Constants ───────────────────────────────────────────────────
MAX_FILE_SIZE_BYTES = 25 * 1024 * 1024  # 25 MB max limit
SUPPORTED_EXTENSIONS = {".pdf", ".ppt", ".pptx", ".txt"}


# =============================================================================
# PYDANTIC SCHEMAS
# =============================================================================

class QuizQuestion(BaseModel):
    question: str = Field(..., description="The quiz question text")
    options: List[str] = Field(..., description="List of 4 multiple-choice options")
    correct_answer: int = Field(..., description="Zero-based index (0, 1, 2, or 3) of the correct option in options")
    explanation: str = Field(..., description="Detailed explanation for why the answer is correct")
    difficulty: Optional[str] = Field(None, description="Easy | Medium | Hard — drives the difficulty-aware skill update at grading")


class QuizPayload(BaseModel):
    questions: List[QuizQuestion] = Field(..., description="List of exactly 5 generated multiple-choice questions")


class DocumentMetadata(BaseModel):
    filename: str = Field(..., description="Original name of the uploaded file")
    file_type: str = Field(..., description="Detected file extension (.pdf, .ppt, .pptx, .txt)")
    file_size_bytes: int = Field(..., description="Size of the uploaded file in bytes")
    character_count: int = Field(..., description="Total extracted character count")
    word_count: int = Field(..., description="Total extracted word count")
    chunk_count: Optional[int] = Field(None, description="Total number of chunks generated by LangChain text splitter")
    page_count: Optional[int] = Field(None, description="Total number of pages (for PDF)")
    slide_count: Optional[int] = Field(None, description="Total number of slides (for PPT/PPTX)")
    line_count: Optional[int] = Field(None, description="Total number of lines (for TXT)")


class DocumentUploadResponse(BaseModel):
    status: str = Field("success", description="Status code or status description ('success' or 'error')")
    message: str = Field(..., description="Human-readable status summary")
    quiz_id: str = Field(..., description="Unique identifier for the generated quiz session")
    filename: str = Field(..., description="Uploaded document filename")
    file_type: str = Field(..., description="Document file type")
    questions: List[QuizQuestion] = Field(..., description="List of 5 generated multiple choice questions based on document text")
    metadata: DocumentMetadata = Field(..., description="Structured metadata of the processed document")


class GradeRequest(BaseModel):
    # FIX (Bug #10): user_id removed from request body.
    # The authenticated user's iGOT userId is derived from current_user.username
    # (populated via JWT in Depends(get_current_user)).
    # Accepting user_id from the body allowed unauthenticated identity spoofing.
    quiz_id: str = Field(..., description="Unique ID of the quiz session being graded")
    answers: List[int] = Field(..., description="List of chosen option indices (0-indexed)")


class GradeResponse(BaseModel):
    status: str = Field("success", description="Status code or status description ('success' or 'error')")
    user_id: str = Field(..., description="User ID of the learner (from JWT)")
    quiz_id: str = Field(..., description="Quiz ID evaluated")
    score: float = Field(..., description="Percentage score achieved (0-100)")
    passed: bool = Field(..., description="True if score >= 70%, False otherwise")
    correct_count: int = Field(..., description="Number of correctly answered questions")
    total_questions: int = Field(..., description="Total number of questions in the quiz")
    message: str = Field(..., description="Human-readable result summary message")
    synced_to_igot: Optional[bool] = Field(None, description="Indicates whether the competency update was pushed to iGOT")
    igot_response: Optional[Dict[str, Any]] = Field(None, description="Response from the mock iGOT server if synced")
    db_updated: Optional[bool] = Field(None, description="Indicates whether the internal SQLite database was updated")
    # FIX (Bug #10): new field — True only on first submission
    evidenceWritten: Optional[bool] = Field(None, description="True if a new EvidenceLog row was written (first submission only)")
    karmaAwarded: Optional[int] = Field(None, description="Karma Points earned by this submission (first pass only)")
    karmaNote: Optional[str] = Field(None, description="Why fewer / no karma points were awarded (daily cap, limit)")
    # Quiz ↔ skill-gap connection (services/practice_assessment.py)
    difficulty: Optional[str] = Field(None, description="Target difficulty the quiz was generated at")
    weighted_score: Optional[float] = Field(None, description="Difficulty-weighted % (Hard = 2x Easy)")
    skillImpact: Optional[Dict[str, Any]] = Field(None, description="Linked role competency, practice ability and skill score/level before → after")
    questionReview: Optional[List[Dict[str, Any]]] = Field(None, description="Per-question result with difficulty, your answer, correct answer, explanation (missed first)")
    recommendations: Optional[Dict[str, Any]] = Field(None, description="Next difficulty, focus topics, courses for the linked competency")




class ErrorResponse(BaseModel):
    status: str = Field("error", description="Failure indicator")
    detail: str = Field(..., description="Error message details")


# =============================================================================
# IN-MEMORY QUIZ STORE
# =============================================================================

QUIZ_STORE: Dict[str, Dict[str, Any]] = {
    "quiz_demo": {
        "quiz_id": "quiz_demo",
        "questions": [
            QuizQuestion(
                question="What is the primary international standard for National Accounts?",
                options=["SNA 2008", "GDP 1993", "IMF 2020", "OECD 2015"],
                correct_answer=0,
                explanation="System of National Accounts (SNA 2008) is the international statistical standard."
            ),
            QuizQuestion(
                question="Which organisation compiles CPI-Combined in India?",
                options=["Reserve Bank of India", "NSO / MoSPI", "NITI Aayog", "Ministry of Finance"],
                correct_answer=1,
                explanation="NSO (National Statistical Office) under MoSPI compiles and releases CPI."
            ),
            QuizQuestion(
                question="What is the base year for the current CPI series in India?",
                options=["2004-05", "2011-12", "2012", "2016"],
                correct_answer=2,
                explanation="The current CPI series has base year 2012 = 100."
            ),
            QuizQuestion(
                question="Which sampling technique gives every unit an equal probability of selection?",
                options=["Simple Random Sampling", "Judgment Sampling", "Quota Sampling", "Snowball Sampling"],
                correct_answer=0,
                explanation="Simple Random Sampling (SRS) ensures equal inclusion probability."
            ),
            QuizQuestion(
                question="What formula is predominantly used for consumer price indices in India?",
                options=["Laspeyres formula", "Fisher ideal index", "Törnqvist index", "Divisia index"],
                correct_answer=0,
                explanation="Laspeyres base-weighted formula is standard in CPI compilation."
            )
        ],
        "filename": "sample_mospi_overview.pdf",
        "competency_id": "FRAC-STAT-001",
        "skill_name": "National Accounts & Official Statistics",
        "difficulty": "Medium",
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
}


# =============================================================================
# TEXT EXTRACTION HELPERS
# =============================================================================

def _clean_text(text: str) -> str:
    """
    Normalizes whitespace, removes null bytes, and cleans up repeated linebreaks.
    """
    if not text:
        return ""
    # Remove null bytes
    text = text.replace("\x00", "")
    # Normalize carriage returns
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    # Replace multiple continuous whitespace (except single newlines)
    text = re.sub(r"[ \t]+", " ", text)
    # Condense 3+ newlines to double newline
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def _extract_pdf(file_bytes: bytes) -> Tuple[str, int]:
    """
    Extracts text from PDF bytes using pdfplumber (primary) with fallback to pypdf.
    Returns a tuple of (extracted_text, page_count).
    """
    try:
        import pdfplumber
    except ImportError:
        pdfplumber = None
    try:
        import pypdf
    except ImportError:
        pypdf = None

    extracted_pages = []
    page_count = 0

    # 1. Attempt extraction with pdfplumber (superior layout & table preservation)
    if pdfplumber is not None:
        try:
            with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
                page_count = len(pdf.pages)
                for idx, page in enumerate(pdf.pages, start=1):
                    page_text = page.extract_text() or ""
                    if page_text.strip():
                        extracted_pages.append(f"--- Page {idx} ---\n{page_text.strip()}")
            
            combined_text = "\n\n".join(extracted_pages)
            if combined_text.strip():
                return _clean_text(combined_text), page_count
        except Exception as e:
            logger.warning(f"pdfplumber failed: {e}. Falling back to pypdf.")
            extracted_pages.clear()

    # 2. Fallback to pypdf
    if pypdf is not None:
        try:
            reader = pypdf.PdfReader(io.BytesIO(file_bytes))
            page_count = len(reader.pages)
            for idx, page in enumerate(reader.pages, start=1):
                page_text = page.extract_text() or ""
                if page_text.strip():
                    extracted_pages.append(f"--- Page {idx} ---\n{page_text.strip()}")
            
            combined_text = "\n\n".join(extracted_pages)
            return _clean_text(combined_text), page_count
        except Exception as e:
            logger.error(f"pypdf extraction failed: {e}")
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail=f"Could not parse PDF content: {str(e)}"
            )

    raise HTTPException(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        detail="No PDF extraction library available on the server (pdfplumber/pypdf)."
    )


def _extract_pptx(file_bytes: bytes) -> Tuple[str, int]:
    """
    Extracts text from PPTX files using python-pptx with XML fallback.
    Returns a tuple of (extracted_text, slide_count).
    """
    try:
        from pptx import Presentation
    except ImportError:
        Presentation = None

    slide_texts = []
    slide_count = 0

    # 1. Primary extraction via python-pptx
    if Presentation is not None:
        try:
            prs = Presentation(io.BytesIO(file_bytes))
            slide_count = len(prs.slides)

            for idx, slide in enumerate(prs.slides, start=1):
                parts = []
                # Extract slide shape texts (titles, textboxes, tables)
                for shape in slide.shapes:
                    if shape.has_text_frame:
                        for paragraph in shape.text_frame.paragraphs:
                            text = "".join(run.text for run in paragraph.runs).strip()
                            if text:
                                parts.append(text)
                    elif shape.has_table:
                        for row in shape.table.rows:
                            row_text = " | ".join(cell.text.strip() for cell in row.cells if cell.text.strip())
                            if row_text:
                                parts.append(row_text)

                # Extract speaker notes if available
                if slide.has_notes_slide and slide.notes_slide.notes_text_frame:
                    notes = slide.notes_slide.notes_text_frame.text.strip()
                    if notes:
                        parts.append(f"[Notes: {notes}]")

                if parts:
                    slide_texts.append(f"--- Slide {idx} ---\n" + "\n".join(parts))

            combined_text = "\n\n".join(slide_texts)
            if combined_text.strip():
                return _clean_text(combined_text), slide_count
        except Exception as e:
            logger.warning(f"python-pptx failed: {e}. Attempting direct XML parsing.")
            slide_texts.clear()

    # 2. Fallback: Parse slide XML files from PPTX (ZIP container) directly
    try:
        with zipfile.ZipFile(io.BytesIO(file_bytes)) as z:
            slide_files = [f for f in z.namelist() if f.startswith("ppt/slides/slide") and f.endswith(".xml")]
            slide_count = len(slide_files)
            # Sort numerically by slide number
            slide_files.sort(key=lambda name: int(re.search(r"\d+", name).group()) if re.search(r"\d+", name) else 0)

            for idx, slide_file in enumerate(slide_files, start=1):
                xml_content = z.read(slide_file)
                tree = ET.fromstring(xml_content)
                # PPTX text elements are in the 'a:t' tags
                texts = [elem.text for elem in tree.iter() if elem.tag.endswith("}t") and elem.text]
                if texts:
                    slide_texts.append(f"--- Slide {idx} ---\n" + "\n".join(texts))

            combined_text = "\n\n".join(slide_texts)
            return _clean_text(combined_text), slide_count
    except Exception as e:
        logger.error(f"PPTX extraction error: {e}")
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"Could not parse PowerPoint presentation: {str(e)}"
        )


def _extract_txt(file_bytes: bytes) -> Tuple[str, int]:
    """
    Extracts text from plain text bytes trying multiple character encodings.
    Returns a tuple of (extracted_text, line_count).
    """
    encodings = ["utf-8", "utf-8-sig", "latin-1", "cp1252", "iso-8859-1"]
    decoded_text = None

    for enc in encodings:
        try:
            decoded_text = file_bytes.decode(enc)
            break
        except UnicodeDecodeError:
            continue

    if decoded_text is None:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="Unable to decode text file. Ensure it is encoded in UTF-8 or standard ASCII."
        )

    cleaned = _clean_text(decoded_text)
    line_count = len(decoded_text.splitlines())
    return cleaned, line_count


def _chunk_document_text(text: str, chunk_size: int = 1000, chunk_overlap: int = 150) -> List[str]:
    """
    Splits extracted document plain-text into semantically coherent chunks using
    LangChain's RecursiveCharacterTextSplitter for RAG processing and vector indexing.
    """
    if not text or not text.strip():
        return []

    from langchain_text_splitters import RecursiveCharacterTextSplitter

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
        separators=["\n\n", "\n", ". ", " ", ""],
        length_function=len,
    )
    return splitter.split_text(text)


def _detect_skill_name(text: str = "", filename: str = "") -> str:
    """
    Infers or extracts the skill/competency topic dynamically from the document's
    filename and text content. Falls back to 'General Statistics' if no match.
    """
    combined = f"{filename} {text[:4000]}".lower()

    if any(k in combined for k in ["machine learning", "supervised learning", "unsupervised learning", "deep learning", "neural network", "classification model"]):
        return "Machine Learning"
    if any(k in combined for k in ["generative ai", "genai", "llm", "large language model", "transformer", "diffusion"]):
        return "Generative AI"
    if any(k in combined for k in ["national account", "gdp", "gross domestic product", "gva", "national income", "macroeconomic indicator"]):
        return "National Accounts"
    if any(k in combined for k in ["data analysis", "data analytics", "exploratory data", "data visualization", "descriptive statistics"]):
        return "Data Analysis"
    if any(k in combined for k in ["index number", "cpi", "wpi", "consumer price index", "wholesale price", "inflation index"]):
        return "Index Numbers"
    if any(k in combined for k in ["sample survey", "sampling design", "nsso", "stratified sampling", "survey methodology", "multistage sampling"]):
        return "Sample Surveys"
    if any(k in combined for k in ["official statistics", "statistical system", "mospi", "cso", "nsso"]):
        return "Official Statistics"
    if any(k in combined for k in ["time series", "forecasting", "arima", "seasonality", "trend analysis"]):
        return "Time Series Analysis"
    if any(k in combined for k in ["python", "pandas", "numpy", "scikit-learn"]):
        return "Python for Data Science"
    if any(k in combined for k in ["sql", "database", "relational database", "query"]):
        return "Database Management"

    return "General Statistics"


def _update_internal_db_competency(
    user_id: str,
    competency_name: str = "General Statistics",
    default_level: int = 3,
    score: float = 0.0,
    quiz_id: str = "",
) -> Tuple[bool, int]:
    """
    Updates the internal auth.db SQLite database via SQLAlchemy models:
    1. Only executed when passed == True.
    2. Uses the correct column name `profileId` (NOT user_id).
    3. Checks if the user exists in the `competency_profiles` table.
    4. If user EXISTS: increases their current_level by 1 (capped at max level 5).
    5. If user DOES NOT EXIST: creates a new record with:
       - profileId = payload.user_id
       - skill_name = dynamically determined skill name
       - current_level = 3 (baseline passing level)
       - target_level = 4
       - updated_at = current timestamp
    6. Explicitly sets these values in INSERT/UPDATE statements so they override database defaults.
    7. Commits changes to the database.
    8. Robust error handling ensures the endpoint never crashes on database errors.
    Returns: (success: bool, final_level: int)
    """
    final_level = default_level
    try:
        Base.metadata.create_all(bind=engine)
        db = SessionLocal()
        try:
            # 1. Find or create Competency for the dynamic skill_name
            comp = db.query(Competency).filter(Competency.skillName == competency_name).first()
            if not comp:
                comp = Competency(
                    compId=f"COMP-{uuid.uuid4().hex[:6].upper()}",
                    domain="Statistical",
                    skillName=competency_name,
                )
                db.add(comp)
                db.flush()

            # 2. Check if user exists in competency_profiles table using profileId
            profile = db.query(CompetencyProfile).filter(CompetencyProfile.profileId == user_id).first()

            if profile:
                logger.info(f"User '{user_id}' EXISTS in competency_profiles. Updating skill '{competency_name}'.")
                profile.skill_name = competency_name
                profile.lastEvaluatedDate = datetime.now(timezone.utc)
                
                # Check UserCompetency record for this profile and competency
                user_comp = db.query(UserCompetency).filter(
                    UserCompetency.profileId == profile.profileId,
                    UserCompetency.compId == comp.compId,
                ).first()

                existing_level = getattr(profile, "current_level", None) or 1

                if user_comp:
                    old_level = user_comp.currentLevel or existing_level or 1
                    final_level = min(old_level + 1, 5)  # increment by 1, capped at max level 5
                    user_comp.currentLevel = final_level
                    user_comp.evaluatedAt = datetime.now(timezone.utc)
                    user_comp.verificationSource = f"RAG Assessment Quiz ({quiz_id})"
                    logger.info(f"User '{user_id}' skill '{competency_name}' increased from Level {old_level} to Level {final_level}")
                else:
                    # User exists in profile table, but first assessment for this skill
                    final_level = default_level  # baseline level 3
                    user_comp = UserCompetency(
                        profileId=profile.profileId,
                        compId=comp.compId,
                        currentLevel=final_level,
                        verificationSource=f"RAG Assessment Quiz ({quiz_id})",
                        evaluatedAt=datetime.now(timezone.utc),
                    )
                    db.add(user_comp)
                    logger.info(f"Created new UserCompetency for user '{user_id}' skill '{competency_name}' at Level {final_level}")

                profile.current_level = final_level
                profile.target_level = min(final_level + 1, 5)
            else:
                logger.info(f"User '{user_id}' DOES NOT EXIST in competency_profiles. Creating new record.")
                final_level = default_level  # baseline level 3
                profile = CompetencyProfile(
                    profileId=user_id,
                    skill_name=competency_name,
                    current_level=final_level,
                    target_level=4,
                    lastEvaluatedDate=datetime.now(timezone.utc),
                )
                db.add(profile)
                db.flush()

                user_comp = UserCompetency(
                    profileId=profile.profileId,
                    compId=comp.compId,
                    currentLevel=final_level,
                    verificationSource=f"RAG Assessment Quiz ({quiz_id})",
                    evaluatedAt=datetime.now(timezone.utc),
                )
                db.add(user_comp)
                logger.info(f"Created new CompetencyProfile with profileId='{user_id}', skill_name='{competency_name}', current_level={final_level}")

            # 3. Save assessment audit entry
            if quiz_id:
                assessment = Assessment(
                    assessmentId=quiz_id,
                    passingScore=70.0,
                    sourceDocumentId=f"RAG Assessment ({competency_name})",
                )
                db.merge(assessment)

            # 4. Commit changes to SQLite auth.db
            db.commit()
            logger.info(f"Successfully committed competency update to auth.db: profileId='{user_id}', skill='{competency_name}', level={final_level}")
            return True, final_level
        except Exception as ex:
            db.rollback()
            logger.exception(f"Failed to update internal auth.db for user {user_id}: {ex}")
            return False, final_level
        finally:
            db.close()
    except Exception as e:
        logger.exception(f"Database connection error updating competency for user {user_id}: {e}")
        return False, final_level


# =============================================================================
# GEMINI QUIZ GENERATION HELPER
# =============================================================================

_DIFFICULTY_GUIDE = {
    "Easy":   "recall and recognition — facts, definitions and terms stated directly in the text; clearly wrong distractors",
    "Medium": "understanding and application — explain, compare, or apply a stated procedure to a simple case",
    "Hard":   "analysis and evaluation — multi-step reasoning, interpreting results, choosing between methods, "
              "spotting an error; all distractors plausible to a partially-prepared reader",
}
_DIFFICULTY_MIX = {"Easy": "3 Easy and 2 Medium", "Medium": "1 Easy, 3 Medium and 1 Hard", "Hard": "1 Medium and 4 Hard"}


async def _generate_mcqs_from_text(text: str, chunks: Optional[List[str]] = None,
                                   difficulty: str = "Medium") -> List[QuizQuestion]:
    """
    Calls Google Gemini API using google-generativeai with GEMINI_API_KEY from .env.
    Generates exactly 5 MCQs based on the extracted text and chunks, enforcing strict JSON output.
    `difficulty` (Easy | Medium | Hard) sets the question mix; each question is
    tagged with its own difficulty, which the grader uses to weight the skill update.
    """
    difficulty = pa.normalise_difficulty(difficulty)
    load_dotenv()
    api_key = os.getenv("GEMINI_API_KEY", "").strip()

    if not api_key or api_key in {"your-actual-api-key-here", "YOUR_GEMINI_API_KEY"}:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="GEMINI_API_KEY is not configured in the .env file. Please configure a valid Gemini API key.",
        )

    import google.generativeai as genai

    try:
        genai.configure(api_key=api_key)
        
        configured_model = os.getenv("GEMINI_MODEL", "gemini-3.5-flash-lite").strip()
        candidate_models = [configured_model] if configured_model else []
        for fallback in ["gemini-3.5-flash-lite", "gemini-3.6-flash", "gemini-3.5-flash", "gemini-flash-latest"]:
            if fallback not in candidate_models:
                candidate_models.append(fallback)

        if chunks and len(chunks) > 0:
            formatted_context = "\n\n---\n\n".join(
                [f"[Document Chunk {idx + 1}/{len(chunks)}]\n{c}" for idx, c in enumerate(chunks[:20])]
            )
        else:
            formatted_context = text[:40000]

        prompt = (
            "You are an expert assessment and quiz creation engine for the Ministry of Statistics and Programme Implementation (MoSPI).\n"
            "Generate exactly 5 multiple-choice questions (MCQs) strictly based on the following training document content chunks.\n\n"
            "Strict Requirements:\n"
            "1. Generate exactly 5 high-quality questions testing comprehension, core concepts, or statistical procedures described in the text.\n"
            "2. Each question MUST contain exactly 4 distinct and plausible options.\n"
            "3. 'correct_answer' MUST be the 0-based integer index of the correct option in the 'options' array (0, 1, 2, or 3).\n"
            "4. Provide a clear, detailed 'explanation' justifying why the selected option is correct according to the text.\n"
            f"5. Target difficulty: {difficulty}. Write {_DIFFICULTY_MIX[difficulty]} question(s), where "
            f"Easy = {_DIFFICULTY_GUIDE['Easy']}; Medium = {_DIFFICULTY_GUIDE['Medium']}; Hard = {_DIFFICULTY_GUIDE['Hard']}.\n"
            "6. Tag every question with its own \"difficulty\": \"Easy\", \"Medium\" or \"Hard\" (honestly — it weights the learner's score).\n"
            "7. Return output conforming strictly to the JSON schema: {\"questions\": [{\"question\": \"...\", \"options\": [\"A\", \"B\", \"C\", \"D\"], \"correct_answer\": 0, \"explanation\": \"...\", \"difficulty\": \"Medium\"}]}.\n\n"
            f"Document Content Chunks:\n\"\"\"\n{formatted_context}\n\"\"\""
        )

        response = None
        last_error = None

        for model_name in candidate_models:
            try:
                model = genai.GenerativeModel(
                    model_name=model_name,
                    generation_config={
                        "response_mime_type": "application/json",
                        "temperature": 0.3,
                    },
                )
                response = await asyncio.to_thread(model.generate_content, prompt)
                if response and response.text:
                    break
            except Exception as ex:
                logger.warning(f"Gemini model '{model_name}' attempt failed: {ex}")
                last_error = ex
                continue

        if not response or not response.text:
            raise ValueError(f"All Gemini model attempts failed. Last error: {last_error}")

        raw_text = response.text.strip()

        # Clean code fence blocks if returned by model
        cleaned_text = raw_text
        if cleaned_text.startswith("```json"):
            cleaned_text = cleaned_text[7:]
        elif cleaned_text.startswith("```"):
            cleaned_text = cleaned_text[3:]
        if cleaned_text.endswith("```"):
            cleaned_text = cleaned_text[:-3]
        cleaned_text = cleaned_text.strip()

        parsed_json = json.loads(cleaned_text)
        if isinstance(parsed_json, dict) and "questions" in parsed_json:
            raw_questions = parsed_json["questions"]
        elif isinstance(parsed_json, list):
            raw_questions = parsed_json
        else:
            raw_questions = [parsed_json]

        normalized_questions: List[QuizQuestion] = []
        for item in raw_questions:
            if not isinstance(item, dict):
                continue
            
            q_text = str(item.get("question") or item.get("question_text") or item.get("prompt") or "").strip()
            if not q_text:
                continue

            raw_opts = item.get("options") or item.get("choices") or item.get("answers") or []
            if isinstance(raw_opts, dict):
                opts = [str(v).strip() for v in raw_opts.values()]
            elif isinstance(raw_opts, list):
                opts = [str(o).strip() for o in raw_opts]
            else:
                opts = [str(raw_opts).strip()]

            opts = [o for o in opts if o]
            while len(opts) < 4:
                opts.append(f"Option {chr(65 + len(opts))}")
            if len(opts) > 4:
                opts = opts[:4]

            raw_ans = item.get("correct_answer") if "correct_answer" in item else (item.get("correctAnswer") if "correctAnswer" in item else item.get("answer"))
            ans_idx = 0
            if isinstance(raw_ans, int):
                ans_idx = max(0, min(len(opts) - 1, raw_ans))
            elif isinstance(raw_ans, str):
                ans_str = raw_ans.strip().upper()
                if ans_str in {"A", "B", "C", "D"}:
                    ans_idx = ord(ans_str) - ord("A")
                elif ans_str.isdigit():
                    ans_idx = max(0, min(len(opts) - 1, int(ans_str)))
                else:
                    for i, opt in enumerate(opts):
                        if opt.lower() == raw_ans.strip().lower():
                            ans_idx = i
                            break

            explanation = str(
                item.get("explanation")
                or item.get("reason")
                or item.get("justification")
                or f"Option {chr(65 + ans_idx)} is the correct answer according to the document."
            ).strip()

            normalized_questions.append(
                QuizQuestion(
                    question=q_text,
                    options=opts,
                    correct_answer=ans_idx,
                    explanation=explanation,
                    difficulty=pa.normalise_difficulty(item.get("difficulty") or item.get("level"), difficulty),
                )
            )

        if not normalized_questions:
            raise ValueError("No valid questions could be extracted from Gemini response.")

        return normalized_questions

    except HTTPException:
        raise
    except json.JSONDecodeError as jde:
        logger.error(f"JSON decode failure from Gemini response: {jde}")
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Failed to parse structured JSON quiz questions from Gemini response: {str(jde)}",
        )
    except Exception as e:
        logger.exception(f"Gemini API generation error: {e}")
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Gemini API error during quiz generation: {str(e)}",
        )


# =============================================================================
# ENDPOINTS
# =============================================================================

@router.post(
    "/upload",
    response_model=DocumentUploadResponse,
    status_code=status.HTTP_200_OK,
    summary="Upload document, extract text, and generate 5 RAG Quiz MCQs with Gemini API",
    responses={
        200: {"description": "Document parsed and 5 MCQs successfully generated via Gemini API."},
        400: {"model": ErrorResponse, "description": "Invalid file format or empty payload."},
        413: {"model": ErrorResponse, "description": "File exceeds maximum size limit."},
        422: {"model": ErrorResponse, "description": "Unprocessable document or no readable text."},
        500: {"model": ErrorResponse, "description": "Internal server processing or configuration error."},
        502: {"model": ErrorResponse, "description": "Gemini API error or bad gateway during generation."},
    },
)
async def upload_document_for_rag(
    file: UploadFile = File(..., description="Document file to process (.pdf, .ppt, .pptx, .txt)"),
    difficulty: str = Form("Medium", description="Easy | Medium | Hard — question mix and grading weights"),
) -> DocumentUploadResponse:
    """
    **RAG Document Ingestion & Quiz Generator**
    
    - Accepts **PDF**, **PPT/PPTX**, and **TXT** files.
    - Validates file extension, MIME type, and size constraints (max 25MB).
    - Extracts clean plain text with page/slide context using **pdfplumber / PyPDF / python-pptx**.
    - Calls Google Gemini API using `google-generativeai` with `GEMINI_API_KEY` from `.env`.
    - Generates exactly **5 MCQs** with strict JSON schema:
      `{"questions": [{"question": "...", "options": ["A", "B", "C", "D"], "correct_answer": 0, "explanation": "..."}]}`.
    - Stores generated quiz in-memory with unique `quiz_id` for grading.
    - Returns the structured quiz payload, quiz_id, and document metadata.
    """
    # 1. Validate presence of filename
    if not file.filename:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No filename provided in upload payload."
        )

    filename = os.path.basename(file.filename)
    _, ext = os.path.splitext(filename.lower())

    # 2. Validate file extension
    if ext not in SUPPORTED_EXTENSIONS:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=(
                f"Unsupported file format '{ext}'. "
                f"Allowed document formats: {', '.join(sorted(SUPPORTED_EXTENSIONS))}"
            )
        )

    # 3. Read file content safely
    try:
        file_bytes = await file.read()
    except Exception as e:
        logger.error(f"Error reading uploaded stream for {filename}: {e}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Failed to read uploaded file: {str(e)}"
        )
    finally:
        await file.close()

    # 4. Validate file size
    file_size = len(file_bytes)
    if file_size == 0:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="The uploaded file is empty (0 bytes)."
        )

    if file_size > MAX_FILE_SIZE_BYTES:
        max_mb = MAX_FILE_SIZE_BYTES // (1024 * 1024)
        raise HTTPException(
            status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
            detail=f"File size exceeds maximum allowed limit of {max_mb} MB."
        )

    # 5. Extract text based on file type
    page_count: Optional[int] = None
    slide_count: Optional[int] = None
    line_count: Optional[int] = None
    extracted_text = ""

    try:
        if ext == ".pdf":
            extracted_text, page_count = _extract_pdf(file_bytes)
        elif ext in {".ppt", ".pptx"}:
            if ext == ".ppt":
                # Check if it's actually a PPTX named .ppt or legacy PPT
                if file_bytes.startswith(b"PK\x03\x04"):
                    extracted_text, slide_count = _extract_pptx(file_bytes)
                else:
                    raise HTTPException(
                        status_code=status.HTTP_400_BAD_REQUEST,
                        detail="Legacy binary .ppt files must be converted to .pptx format or PDF."
                    )
            else:
                extracted_text, slide_count = _extract_pptx(file_bytes)
        elif ext == ".txt":
            extracted_text, line_count = _extract_txt(file_bytes)

    except HTTPException:
        raise
    except Exception as e:
        logger.exception(f"Unexpected error extracting text from {filename}: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Internal error processing document: {str(e)}"
        )

    # 6. Verify that readable text was obtained
    if not extracted_text or len(extracted_text.strip()) == 0:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=(
                "No readable text could be extracted from this document. "
                "If this is a scanned PDF/image, please provide a document with OCR/selectable text."
            )
        )

    # 6. Chunk extracted text using LangChain TextSplitter
    chunks = _chunk_document_text(extracted_text, chunk_size=1000, chunk_overlap=150)
    chunk_count = len(chunks)

    # 7. Generate exactly 5 MCQs via Google Gemini API from text and chunks
    difficulty = pa.normalise_difficulty(difficulty)
    questions = await _generate_mcqs_from_text(extracted_text, chunks=chunks, difficulty=difficulty)

    # 8. Generate unique quiz ID and store in-memory for subsequent grading
    inferred_skill = _detect_skill_name(text=extracted_text, filename=filename)
    quiz_id = f"QZ-{uuid.uuid4().hex[:8].upper()}"
    QUIZ_STORE[quiz_id] = {
        "quiz_id": quiz_id,
        "questions": questions,
        "filename": filename,
        "extracted_text": extracted_text[:4000],
        "chunks": chunks,
        "chunk_count": chunk_count,
        # No hardcoded FRAC id any more: /grade links the quiz to the learner's
        # own role competency (practice_assessment.link_competency).
        "competency_id": None,
        "skill_name": inferred_skill,
        "difficulty": difficulty,
        "created_at": datetime.now(timezone.utc).isoformat(),
    }

    # 9. Compute statistics & build response metadata
    char_count = len(extracted_text)
    word_count = len(extracted_text.split())

    metadata = DocumentMetadata(
        filename=filename,
        file_type=ext,
        file_size_bytes=file_size,
        character_count=char_count,
        word_count=word_count,
        chunk_count=chunk_count,
        page_count=page_count,
        slide_count=slide_count,
        line_count=line_count,
    )

    return DocumentUploadResponse(
        status="success",
        message=f"Successfully chunked ({chunk_count} chunks) and generated {len(questions)} {difficulty}-level quiz questions from {filename}.",
        quiz_id=quiz_id,
        filename=filename,
        file_type=ext,
        questions=questions,
        metadata=metadata,
    )


def _question_difficulties(quiz: Dict[str, Any]) -> List[str]:
    """Per-question difficulty: the question's own tag, else the quiz's target difficulty."""
    quiz_difficulty = pa.normalise_difficulty(quiz.get("difficulty"))
    return [pa.normalise_difficulty(getattr(q, "difficulty", None), quiz_difficulty)
            for q in quiz.get("questions", [])]


def _row_snapshot(row: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    if not row:
        return {}
    level, target = row.get("currentLevel"), row.get("targetLevel")
    return {
        "level": level,
        "score": round(float(row.get("rawScore") or 0.0), 3),
        "confidence": row.get("confidence"),
        "basis": row.get("basis"),
        "targetLevel": target,
        "gap": (max(0, int(target) - int(level)) if level is not None and target is not None else None),
    }


def _record_attempt(
    user_id: str, quiz_id: str, quiz: Dict[str, Any], answers: List[int], score: float, weighted: float,
    passed: bool, results: List[Dict[str, Any]], row: Optional[Dict[str, Any]], link: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Sync DB work for /grade (runs in a worker thread).

    First submission of a quiz → one QuizAttempt row and, pass OR fail, one
    PRACTICE_ASSESSMENT EvidenceLog row whose value is the learner's updated
    practice ability θ for the linked competency (practice_assessment.update_ability).
    Re-submissions of the same quiz are scored for UX only — no second row, so
    retaking a quiz whose answers you have now seen cannot farm the skill level.
    """
    out: Dict[str, Any] = {"firstAttempt": False, "evidenceWritten": False}
    db = SessionLocal()
    try:
        if db.query(QuizAttempt).filter(QuizAttempt.userId == user_id, QuizAttempt.quizId == quiz_id).first():
            return out
        out["firstAttempt"] = True

        # Evidence is keyed by the catalogue id when the role competency is
        # crosswalked (the assembler reads both ids), else the role id; with no
        # linked role competency, by the quiz's own FRAC tag or its skill name.
        comp_id = (row.get("catalogueId") or row.get("competencyId")) if row else quiz.get("competency_id")
        comp_name = (row.get("name") if row else None) or quiz.get("skill_name") or "General Statistics"
        comp_obj = db.query(Competency).filter(Competency.compId == comp_id).first() if comp_id else None
        if not comp_obj and not comp_id:
            comp_obj = db.query(Competency).filter(Competency.skillName == comp_name).first()
        if not comp_obj:
            comp_obj = Competency(compId=comp_id or f"COMP-{uuid.uuid4().hex[:6].upper()}",
                                  domain="Statistical", skillName=comp_name)
            db.add(comp_obj)
            db.flush()

        ids = {i for i in ((row or {}).get("competencyId"), (row or {}).get("catalogueId"), comp_obj.compId) if i}
        prior_rows = [
            {"evidence_type": e.evidenceType, "granted_value": e.grantedValue, "issue_date": e.issueDate}
            for e in db.query(EvidenceLog).filter(
                EvidenceLog.userId == user_id,
                EvidenceLog.evidenceType == "PRACTICE_ASSESSMENT",
                EvidenceLog.compId.in_(ids),
            ).all()
        ]
        prior, _ = pa.latest_practice_value(prior_rows)
        theta0, start_basis = pa.starting_ability(prior, row)
        theta1, trace = pa.update_ability(theta0, results)

        attempt = QuizAttempt(userId=user_id, quizId=quiz_id, compId=comp_obj.compId, answers=answers,
                              score=score, passed=passed, evidenceWritten=False)
        db.add(attempt)
        db.flush()
        db.add(EvidenceLog(
            userId=user_id, compId=comp_obj.compId, evidenceType="PRACTICE_ASSESSMENT",
            grantedValue=theta1, issueDate=datetime.now(timezone.utc),
            metadata_payload={
                "source": "assessment_studio_quiz",
                "quiz_id": quiz_id,
                "title": quiz.get("filename"),
                "quiz_source": quiz.get("source_type", "document"),
                "competencyName": comp_name,
                "difficulty": pa.normalise_difficulty(quiz.get("difficulty")),
                "score": score,
                "weighted_score": weighted,
                "passed": passed,
                "pass_threshold": pa.PASS_THRESHOLD,
                "ability_before": round(theta0, 3),
                "ability_after": theta1,
                "start_basis": start_basis,
                "per_question": trace,
                "link": link,
            },
        ))
        attempt.evidenceWritten = True
        db.commit()
        out.update({
            "evidenceWritten": True, "compId": comp_obj.compId, "competencyName": comp_name,
            "abilityBefore": round(theta0, 3), "abilityAfter": theta1,
            "abilityDelta": round(theta1 - theta0, 3), "startBasis": start_basis, "perQuestion": trace,
        })
        logger.info("[grade_quiz] practice evidence: user=%s comp=%s θ %.2f → %.2f (score %.0f%%)",
                    user_id, comp_obj.compId, theta0, theta1, score)
        return out
    except Exception as exc:
        db.rollback()
        logger.exception("[grade_quiz] DB error during QuizAttempt/EvidenceLog write: %s", exc)
        out["error"] = str(exc)
        return out
    finally:
        db.close()


async def _competency_rows(user_id: str) -> Optional[List[Dict[str, Any]]]:
    """The learner's resolved role competencies (same rows the skill-gap view shows), or None."""
    if app_state.competency_state is None:
        return None
    try:
        state = await app_state.competency_state(user_id, annotate=False)
        return list(state.get("competencies") or [])
    except Exception as exc:
        logger.warning("[grade_quiz] competency state unavailable for %s: %s", user_id, exc)
        return None


@router.post(
    "/grade",
    response_model=GradeResponse,
    status_code=status.HTTP_200_OK,
    summary="Grade a quiz, update the learner's practice ability on the linked competency, and recommend next steps",
    responses={
        200: {"description": "Quiz evaluated successfully."},
        400: {"model": ErrorResponse, "description": "Invalid submission or answers format."},
        401: {"model": ErrorResponse, "description": "Authentication required."},
        404: {"model": ErrorResponse, "description": "Quiz session not found."},
        500: {"model": ErrorResponse, "description": "Internal grading error."},
    },
)
async def grade_quiz(
    payload: GradeRequest,
    current_user: UserAuth = Depends(get_current_user),   # FIX (Bug #10): auth required
) -> GradeResponse:
    """
    **Grade Quiz → Skill Gap**

    - user_id comes from the JWT (current_user.username), never the body (Bug #10).
    - The quiz is linked to one of the learner's ROLE competencies (FRAC tag →
      e5 similarity → keyword overlap; practice_assessment.link_competency).
    - Every question moves the learner's practice ability θ by a
      difficulty-aware step: missing an Easy question costs more than missing a
      Hard one; solving a Hard one gains more than solving an Easy one.
    - First submission (pass or fail) writes one PRACTICE_ASSESSMENT EvidenceLog
      row = θ after; the baseline assembler reads the latest one into the
      documented channel, so the skill score moves up or down a bounded amount.
      Re-submissions are re-scored for UX only (QuizAttempt UNIQUE(userId, quizId)).
    - Pass (≥ 70 %) still awards karma, updates the legacy CompetencyProfile
      table and syncs to iGOT.
    - The response carries the before → after skill impact, a question review
      and recommendations (next difficulty, focus topics, courses).
    """
    igot_user_id = current_user.username   # e.g. "usr_720465595"

    quiz = QUIZ_STORE.get(payload.quiz_id)
    if not quiz:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Quiz session '{payload.quiz_id}' not found. Please upload a document to generate a quiz.",
        )
    questions: List[QuizQuestion] = quiz.get("questions", [])
    total_questions = len(questions)
    if total_questions == 0:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST,
                            detail="The specified quiz contains no questions to grade.")
    if not payload.answers:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST,
                            detail="No answers provided in submission payload.")

    # 1. Score — plain % (pass rule) and difficulty-weighted %
    quiz_difficulty = pa.normalise_difficulty(quiz.get("difficulty"))
    difficulties = _question_difficulties(quiz)
    results = [
        {"difficulty": difficulties[i],
         "correct": i < len(payload.answers) and payload.answers[i] == q.correct_answer}
        for i, q in enumerate(questions)
    ]
    correct_count = sum(r["correct"] for r in results)
    score_percentage = round((correct_count / total_questions) * 100.0, 2)
    weighted = pa.weighted_score(results)
    passed = score_percentage >= pa.PASS_THRESHOLD

    # 2. Link the quiz to the learner's role competency (the skill-gap rows)
    rows_before = await _competency_rows(igot_user_id)
    engine = app_state.engine
    descriptions = {cid: m.get("description", "") for cid, m in (getattr(engine, "_frac_map", None) or {}).items()}
    row_before, link_method, link_score = await asyncio.to_thread(
        pa.link_competency, rows_before or [], quiz, descriptions)
    link = {"method": link_method, "score": link_score,
            "competencyId": row_before.get("competencyId") if row_before else None}

    # 3. Persist attempt + practice evidence (first submission only)
    rec = await asyncio.to_thread(
        _record_attempt, igot_user_id, payload.quiz_id, quiz, payload.answers, score_percentage,
        weighted, passed, results, row_before, link)
    evidence_written = rec["evidenceWritten"]

    # 4. Re-resolve the skill gap so the learner sees the effect immediately
    row_after = None
    if evidence_written:
        app_state.invalidate_user(igot_user_id)
        if row_before:
            rows_after = await _competency_rows(igot_user_id)
            row_after = next((r for r in rows_after or [] if r.get("competencyId") == row_before["competencyId"]), None)

    before, after = _row_snapshot(row_before), _row_snapshot(row_after or row_before)
    skill_impact: Dict[str, Any] = {
        "recorded": evidence_written,
        "linkedToSkillGap": row_before is not None,
        "competencyId": row_before.get("competencyId") if row_before else rec.get("compId"),
        "competencyName": row_before.get("name") if row_before else (rec.get("competencyName") or quiz.get("skill_name")),
        "linkMethod": link_method,
        "linkScore": link_score,
        "before": before,
        "after": after,
    }
    if evidence_written:
        skill_impact.update({k: rec[k] for k in ("abilityBefore", "abilityAfter", "abilityDelta",
                                                   "startBasis", "perQuestion")})
        if before and after:
            skill_impact["scoreDelta"] = round(after["score"] - before["score"], 3)
            if before.get("level") is not None and after.get("level") is not None:
                skill_impact["levelDelta"] = after["level"] - before["level"]
    elif not rec["firstAttempt"]:
        skill_impact["note"] = ("You already submitted this quiz — practice evidence is recorded once per quiz. "
                                "Generate a new quiz to move your skill level again.")
    elif rec.get("error"):
        skill_impact["note"] = "Could not record practice evidence (database unavailable)."

    # 5. Karma (first pass only)
    karma_result = None
    if passed and rec["firstAttempt"] and evidence_written:
        from models.models import KarmaEventType
        from services.karma_engine import karma_engine
        karma_result = await asyncio.to_thread(
            karma_engine.award_safe, igot_user_id, KarmaEventType.ASSESSMENT_PASSED,
            {"referenceId": payload.quiz_id, "note": skill_impact["competencyName"] or quiz.get("filename") or "Quiz passed"})

    # 6. Review + recommendations
    review = pa.review_topics(questions, payload.answers, difficulties)
    next_diff, next_reason = pa.next_difficulty(quiz_difficulty, weighted)
    focus = [r["question"] for r in review if not r["correct"]][:5]
    catalogue_id = (row_before or {}).get("catalogueId") or (row_before or {}).get("competencyId") or quiz.get("competency_id")
    courses = pa.suggest_courses(engine, catalogue_id, after.get("level"), after.get("targetLevel"))
    name = skill_impact["competencyName"] or "this topic"
    if after.get("gap"):
        summary = (f"{name}: you are at Level {after['level']} of the Level {after['targetLevel']} your role needs "
                   f"(gap {after['gap']}).")
    elif after.get("level") is not None and after.get("targetLevel") is not None:
        summary = f"{name}: you meet your role's Level {after['targetLevel']} — keep the skill fresh with harder quizzes."
    else:
        summary = f"{name}: not one of your role competencies, so this quiz does not change your skill gap."
    if focus:
        summary += f" Revise the {len(focus)} question{'s' if len(focus) != 1 else ''} you missed first."
    recommendations = {"nextDifficulty": next_diff, "nextDifficultyReason": next_reason,
                       "focusTopics": focus, "courses": courses, "summary": summary}

    # 7. Pass → legacy CompetencyProfile table + iGOT sync
    synced_to_igot: Optional[bool] = None
    igot_response_data: Optional[Dict[str, Any]] = None
    db_updated: Optional[bool] = None
    if passed:
        skill_name = skill_impact["competencyName"] or quiz.get("skill_name") or "General Statistics"
        db_updated, legacy_level = _update_internal_db_competency(
            user_id=igot_user_id, competency_name=skill_name, default_level=3,
            score=score_percentage, quiz_id=payload.quiz_id,
        )
        igot_url = os.getenv("IGOT_COMPETENCIES_UPDATE_URL", "http://localhost:8001/competencies/update")
        igot_token = os.getenv("IGOT_MOCK_TOKEN", "mock-api-key-2026")
        update_payload = {
            "user_id": igot_user_id,
            "competency": skill_name,
            "competency_id": skill_impact["competencyId"],
            "new_level": after.get("level") if after.get("level") is not None else legacy_level,
        }
        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                resp = await client.post(igot_url, json=update_payload,
                                         headers={"x-authenticated-user-token": igot_token})
            synced_to_igot = resp.status_code in (200, 201)
            try:
                igot_response_data = resp.json()
            except Exception:
                igot_response_data = {"status_code": resp.status_code, "raw": resp.text}
        except httpx.RequestError as exc:
            synced_to_igot = False
            igot_response_data = {"warning": f"iGOT server unreachable at {igot_url}: {str(exc)}"}

    # 8. Message
    msg = (f"{'Passed' if passed else 'Not passed'} — {score_percentage:g}% ({correct_count}/{total_questions} correct), "
           f"{weighted:g}% difficulty-weighted.")
    if evidence_written and "abilityDelta" in skill_impact:
        d = skill_impact["abilityDelta"]
        msg += (f" {name} practice ability {skill_impact['abilityBefore']:.2f} → {skill_impact['abilityAfter']:.2f}"
                f" ({'+' if d >= 0 else ''}{d:.2f}).")
    elif skill_impact.get("note"):
        msg += " " + skill_impact["note"]
    if karma_result and karma_result.points_awarded > 0:
        msg += f" +{karma_result.points_awarded} Karma Points earned."
    if not passed:
        msg += f" {pa.PASS_THRESHOLD:g}% is needed to pass."

    return GradeResponse(
        status="success",
        user_id=igot_user_id,
        quiz_id=payload.quiz_id,
        score=score_percentage,
        passed=passed,
        correct_count=correct_count,
        total_questions=total_questions,
        message=msg,
        synced_to_igot=synced_to_igot,
        igot_response=igot_response_data,
        db_updated=db_updated,
        evidenceWritten=evidence_written,
        karmaAwarded=karma_result.points_awarded if karma_result else None,
        karmaNote=karma_result.reason if karma_result else None,
        difficulty=quiz_difficulty,
        weighted_score=weighted,
        skillImpact=skill_impact,
        questionReview=review,
        recommendations=recommendations,
    )


@router.get("/attempts", summary="The signed-in learner's graded quiz attempts, newest first")
async def list_attempts(current_user: UserAuth = Depends(get_current_user)) -> Dict[str, Any]:
    """Assessment Studio history: QuizAttempt rows joined with their practice evidence (skill impact)."""
    user_id = current_user.username

    def _load() -> List[Dict[str, Any]]:
        db = SessionLocal()
        try:
            attempts = (db.query(QuizAttempt).filter(QuizAttempt.userId == user_id)
                        .order_by(QuizAttempt.gradedAt.desc()).limit(100).all())
            evidence = {}
            for e in db.query(EvidenceLog).filter(EvidenceLog.userId == user_id,
                                                  EvidenceLog.evidenceType == "PRACTICE_ASSESSMENT").all():
                meta = e.metadata_payload or {}
                if meta.get("quiz_id"):
                    evidence[meta["quiz_id"]] = meta
            names = {c.compId: c.skillName for c in db.query(Competency).filter(
                Competency.compId.in_({a.compId for a in attempts if a.compId})).all()} if attempts else {}
            out = []
            for a in attempts:
                meta = evidence.get(a.quizId, {})
                stored = QUIZ_STORE.get(a.quizId) or {}
                out.append({
                    "id": a.attemptId,
                    "quizId": a.quizId,
                    "title": meta.get("title") or stored.get("filename") or a.quizId,
                    "date": a.gradedAt.isoformat() if a.gradedAt else None,
                    "score": a.score,
                    "passed": a.passed,
                    "weightedScore": meta.get("weighted_score"),
                    "difficulty": meta.get("difficulty") or stored.get("difficulty"),
                    "competencyId": a.compId,
                    "competencyName": meta.get("competencyName") or names.get(a.compId),
                    "abilityBefore": meta.get("ability_before"),
                    "abilityAfter": meta.get("ability_after"),
                })
            return out
        finally:
            db.close()

    try:
        return {"status": "success", "attempts": await asyncio.to_thread(_load)}
    except Exception as exc:
        logger.exception("[attempts] %s", exc)
        return {"status": "error", "attempts": []}
